# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A safe approach to CAS and other atomic ops in Haskell"
HOMEPAGE="https://github.com/rrnewton/haskell-lockfree-queue/wiki"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="debug foreign"

RDEPEND="dev-haskell/cabal:=[profile?]
	dev-haskell/primitive:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	foreign? ( dev-haskell/bits-atomic:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag debug debug) \
		$(cabal_flag foreign foreign)
}
