# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="GPipe-Examples"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Examples for the GPipes package"
HOMEPAGE="http://hackage.haskell.org/package/GPipe-Examples"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/glut:=
	dev-haskell/gpipe:=
	dev-haskell/gpipe-textureload:=
	dev-haskell/vec:=
	dev-haskell/vec-transform:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
