# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="QuadTree"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="QuadTree library for Haskell, with lens support"
HOMEPAGE="http://hackage.haskell.org/package/QuadTree"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/composition-1.0:=[profile?] <dev-haskell/composition-1.1:=[profile?]
	>=dev-haskell/lens-4.0:=[profile?] <dev-haskell/lens-4.1:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
