# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Nomyx-Core"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Nomic game in haskell"
HOMEPAGE="http://www.nomyx.net"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/acid-state-0.12:=[profile?] <dev-haskell/acid-state-0.13:=[profile?]
	>=dev-haskell/aeson-0.7:=[profile?] <dev-haskell/aeson-0.8:=[profile?]
	>=dev-haskell/blaze-html-0.7:=[profile?] <dev-haskell/blaze-html-0.8:=[profile?]
	>=dev-haskell/blaze-markup-0.6:=[profile?] <dev-haskell/blaze-markup-0.7:=[profile?]
	>=dev-haskell/data-lens-2.10:=[profile?] <dev-haskell/data-lens-2.11:=[profile?]
	>=dev-haskell/data-lens-fd-2.0:=[profile?] <dev-haskell/data-lens-fd-2.1:=[profile?]
	>=dev-haskell/data-lens-template-2.1:=[profile?] <dev-haskell/data-lens-template-2.2:=[profile?]
	>=dev-haskell/debugtracehelpers-0.12:=[profile?] <dev-haskell/debugtracehelpers-0.13:=[profile?]
	>=dev-haskell/either-unwrap-1.1:=[profile?] <dev-haskell/either-unwrap-1.2:=[profile?]
	>=dev-haskell/exceptions-0.3:=[profile?] <dev-haskell/exceptions-0.4:=[profile?]
	>=dev-haskell/happstack-authenticate-0.10:=[profile?] <dev-haskell/happstack-authenticate-0.11:=[profile?]
	>=dev-haskell/hint-0.4:=[profile?] <dev-haskell/hint-0.5:=[profile?]
	>=dev-haskell/hint-server-1.3:=[profile?] <dev-haskell/hint-server-1.4:=[profile?]
	>=dev-haskell/hscolour-1.20:=[profile?] <dev-haskell/hscolour-1.21:=[profile?]
	>=dev-haskell/ixset-1.0:=[profile?] <dev-haskell/ixset-1.1:=[profile?]
	>=dev-haskell/mime-mail-0.4:=[profile?] <dev-haskell/mime-mail-0.5:=[profile?]
	>=dev-haskell/missingh-1.2:=[profile?] <dev-haskell/missingh-1.3:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/network-2.4:=[profile?] <dev-haskell/network-2.5:=[profile?]
	~dev-haskell/nomyx-language-0.6.0:=[profile?]
	>=dev-haskell/old-locale-1.0:=[profile?] <dev-haskell/old-locale-1.1:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?] <dev-haskell/safe-0.4:=[profile?]
	>=dev-haskell/safecopy-0.8:=[profile?] <dev-haskell/safecopy-0.9:=[profile?]
	>=dev-haskell/stm-2.4:=[profile?] <dev-haskell/stm-2.5:=[profile?]
	>=dev-haskell/tar-0.4:=[profile?] <dev-haskell/tar-0.5:=[profile?]
	>=dev-haskell/temporary-1.1:=[profile?] <dev-haskell/temporary-1.2:=[profile?]
	>=dev-haskell/text-1.1:=[profile?] <dev-haskell/text-1.2:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
