# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="AWS SDK for Haskell"
HOMEPAGE="http://worksap-ate.github.com/aws-sdk"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="debug"

RDEPEND=">=dev-haskell/base64-bytestring-1.0.0.0:=[profile?]
	>=dev-haskell/conduit-0.5.3:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/http-conduit:=[profile?]
	dev-haskell/http-types:=[profile?]
	>=dev-haskell/iproute-1.2.9:=[profile?]
	dev-haskell/lifted-base:=[profile?]
	dev-haskell/monad-control:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/old-locale:=[profile?]
	dev-haskell/parallel:=[profile?]
	dev-haskell/parsec:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/sha:=[profile?]
	>=dev-haskell/simple-config-1.1.1.0:=[profile?]
	dev-haskell/strptime:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/transformers:=[profile?]
	dev-haskell/transformers-base:=[profile?]
	>=dev-haskell/xml-conduit-1.0.3.3:=[profile?]
	dev-haskell/xml-types:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( dev-haskell/hspec
		dev-haskell/hunit
		dev-haskell/quickcheck
		dev-haskell/tls )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag debug debug)
}
