# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="MissingM"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="findM and other missing 'M's"
HOMEPAGE="http://hackage.haskell.org/package/MissingM"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.14
	test? ( >=dev-haskell/hunit-1.2 <dev-haskell/hunit-2
		>=dev-haskell/quickcheck-2.4
		>=dev-haskell/test-framework-0.4.1
		dev-haskell/test-framework-hunit
		dev-haskell/test-framework-quickcheck2
		>dev-haskell/transformers-0.3 )
"

S="${WORKDIR}/${MY_P}"
