# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Continuous integration system"
HOMEPAGE="https://github.com/ndmitchell/bake#readme"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
	>=dev-haskell/cmdargs-0.10:=[profile?]
	>=dev-haskell/extra-0.3:=[profile?]
	dev-haskell/hashable:=[profile?]
	dev-haskell/http:=[profile?]
	dev-haskell/http-types:=[profile?]
	dev-haskell/random:=[profile?]
	>=dev-haskell/shake-0.10:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-haskell/wai-3.0.1:=[profile?]
	>=dev-haskell/warp-3.0:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"
