# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Hieroglyph"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Purely functional 2D drawing"
HOMEPAGE="http://vis.renci.org/jeff/hieroglyph"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/buster:=[profile?]
	dev-haskell/cairo:=[profile?]
	dev-haskell/colour:=[profile?]
	dev-haskell/ftgl:=[profile?]
	dev-haskell/gtk:=[profile?]
	dev-haskell/gtkglext:=[profile?]
	dev-haskell/ifelse:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/opengl:=[profile?]
	dev-haskell/parallel:=[profile?]
	dev-haskell/random:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
