# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A Webmachine-inspired HTTP library"
HOMEPAGE="http://hackage.haskell.org/package/airship"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/attoparsec:=[profile?]
	>=dev-haskell/blaze-builder-0.3:=[profile?] <dev-haskell/blaze-builder-0.4:=[profile?]
	dev-haskell/case-insensitive:=[profile?]
	>=dev-haskell/either-4.3:=[profile?] <dev-haskell/either-4.4:=[profile?]
	dev-haskell/http-date:=[profile?]
	dev-haskell/http-media:=[profile?]
	>=dev-haskell/http-types-0.7:=[profile?]
	>=dev-haskell/lifted-base-0.2:=[profile?] <dev-haskell/lifted-base-0.3:=[profile?]
	>=dev-haskell/monad-control-1.0:=[profile?]
	>=dev-haskell/mtl-2.2:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	dev-haskell/network:=[profile?]
	dev-haskell/old-locale:=[profile?]
	dev-haskell/random:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-haskell/transformers-0.4.2:=[profile?] <dev-haskell/transformers-0.4.3:=[profile?]
	>=dev-haskell/transformers-base-0.4.3:=[profile?] <dev-haskell/transformers-base-0.4.4:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-haskell/wai-3.0.2:=[profile?] <dev-haskell/wai-3.0.3:=[profile?]
	>=dev-haskell/warp-3.0.5:=[profile?] <dev-haskell/warp-3.0.6:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/tasty-0.10 <dev-haskell/tasty-0.11
		>=dev-haskell/tasty-hunit-0.9.1 <dev-haskell/tasty-hunit-0.10
		>=dev-haskell/tasty-quickcheck-0.8.3 <dev-haskell/tasty-quickcheck-0.8.4
		>=dev-haskell/text-1.2 <dev-haskell/text-1.3 )
"
