# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Nomyx-Language"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Language to express rules for Nomic"
HOMEPAGE="http://www.nomyx.net"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/boolean-0.2:=[profile?] <dev-haskell/boolean-0.3:=[profile?]
	>=dev-haskell/data-lens-2.10:=[profile?] <dev-haskell/data-lens-2.11:=[profile?]
	>=dev-haskell/data-lens-fd-2.0:=[profile?] <dev-haskell/data-lens-fd-2.1:=[profile?]
	>=dev-haskell/data-lens-template-2.1:=[profile?] <dev-haskell/data-lens-template-2.2:=[profile?]
	>=dev-haskell/debugtracehelpers-0.12:=[profile?] <dev-haskell/debugtracehelpers-0.13:=[profile?]
	>=dev-haskell/ghc-7.6:=[profile?] <=dev-haskell/ghc-7.10:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/old-locale-1.0:=[profile?] <dev-haskell/old-locale-1.1:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?] <dev-haskell/safe-0.4:=[profile?]
	>=dev-haskell/time-recurrence-0.9:=[profile?] <dev-haskell/time-recurrence-0.10:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
