# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Nomyx-Language"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Language to express rules for Nomic"
HOMEPAGE="http://hackage.haskell.org/package/Nomyx-Language"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/boolean:=[profile?]
	dev-haskell/data-lens:=[profile?]
	dev-haskell/data-lens-fd:=[profile?]
	dev-haskell/data-lens-template:=[profile?]
	dev-haskell/debugtracehelpers:=[profile?]
	dev-haskell/ghc:=[profile?]
	dev-haskell/hint-server:=[profile?]
	dev-haskell/hslogger:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/old-locale:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/safecopy:=[profile?]
	dev-haskell/stm:=[profile?]
	dev-haskell/time-recurrence:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
