# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="ScratchFs"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Size limited temp filesystem based on fuse"
HOMEPAGE="http://github.com/hirschenberger/ScratchFS"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/hfuse-0.2.4:=
	>=dev-haskell/hsyslog-1.4:=
	>=dev-haskell/regex-compat-0.95:=
	>=dev-haskell/sqlite-simple-0.2:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
