# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Fast rendering of common datatypes"
HOMEPAGE="http://github.com/bos/blaze-textual"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="developer +native"

RDEPEND=">=dev-haskell/blaze-builder-0.2.1.4:=[profile?]
	dev-haskell/old-locale:=[profile?]
	>=dev-haskell/text-0.11.0.2:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	!native? ( >=dev-haskell/double-conversion-0.2.0.1:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/quickcheck-2.4.0.1
		>=dev-haskell/test-framework-0.3.3
		>=dev-haskell/test-framework-quickcheck2-0.2.9
		native? ( dev-haskell/double-conversion ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag developer developer) \
		$(cabal_flag native native)
}
