# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Commando"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Watch some files; Rerun a command"
HOMEPAGE="https://github.com/sordina/Commando"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/fsnotify-0.0.10:=[profile?] <dev-haskell/fsnotify-0.1:=[profile?]
	>=dev-haskell/optparse-applicative-0.5:=[profile?] <dev-haskell/optparse-applicative-0.6:=[profile?]
	>=dev-haskell/system-fileio-0.3:=[profile?] <dev-haskell/system-fileio-0.4:=[profile?]
	>=dev-haskell/system-filepath-0.4:=[profile?] <dev-haskell/system-filepath-0.5:=[profile?]
	>=dev-haskell/text-0.10:=[profile?] <dev-haskell/text-0.12:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
