# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Paraiso"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="a code generator for partial differential equations solvers"
HOMEPAGE="http://www.paraiso-lang.org/wiki/index.php/Main_Page"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+test"

RDEPEND=">=dev-haskell/control-monad-failure-0.7.0:=[profile?]
	>=dev-haskell/fgl-5.4.2:=[profile?]
	>=dev-haskell/listlike-3.1.1:=[profile?]
	>=dev-haskell/listlike-instances-0.1:=[profile?]
	>=dev-haskell/mtl-2.0.1:=[profile?]
	>=dev-haskell/numeric-prelude-0.2:=[profile?]
	>=dev-haskell/random-1.0.0:=[profile?]
	>=dev-haskell/text-0.11.1:=[profile?]
	>=dev-haskell/typelevel-tensor-0.1:=[profile?]
	>=dev-haskell/vector-0.7.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	test? ( dev-haskell/hunit
		>=dev-haskell/quickcheck-2
		dev-haskell/test-framework
		dev-haskell/test-framework-hunit
		dev-haskell/test-framework-quickcheck2 )
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag test test)
}
