# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="ADPfusion"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Efficient, high-level dynamic programming"
HOMEPAGE="http://www.tbi.univie.ac.at/~choener/adpfusion"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="devel"

RDEPEND=">=dev-haskell/primitive-0.5:=[profile?] <dev-haskell/primitive-0.6:=[profile?]
	>=dev-haskell/primitivearray-0.4:=[profile?] <dev-haskell/primitivearray-0.5:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?] <dev-haskell/vector-0.11:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	devel? ( >=dev-haskell/criterion-0.6:=[profile?] <dev-haskell/criterion-0.7:=[profile?]
			~dev-haskell/quickcheck-2.5:2=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6.0
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag devel devel)
}
