# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Hmpf"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An MPD client designed for a Home Theatre PC"
HOMEPAGE="http://hackage.haskell.org/package/Hmpf"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/configfile:=
	dev-haskell/crypto:=
	dev-haskell/http:=
	dev-haskell/mtl:=
	dev-haskell/network:=
	dev-haskell/utf8-string:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"
