# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Accelerate frontend to the CUFFT library (Fourier transform)"
HOMEPAGE="http://code.haskell.org/~thielema/accelerate-cufft/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="buildexamples"

RDEPEND=">=dev-haskell/accelerate-0.15:=[profile?] <dev-haskell/accelerate-0.16:=[profile?]
	>=dev-haskell/accelerate-cuda-0.15:=[profile?] <dev-haskell/accelerate-cuda-0.16:=[profile?]
	>=dev-haskell/accelerate-fourier-0.0:=[profile?] <dev-haskell/accelerate-fourier-0.1:=[profile?]
	>=dev-haskell/accelerate-utility-0.1:=[profile?] <dev-haskell/accelerate-utility-0.2:=[profile?]
	>=dev-haskell/cuda-0.5:=[profile?] <dev-haskell/cuda-0.7:=[profile?]
	>=dev-haskell/cufft-0.1.1:=[profile?] <dev-haskell/cufft-0.2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.14
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag buildexamples buildexamples)
}
