# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Graph500"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Graph500 benchmark-related definitions and data set generator"
HOMEPAGE="http://hackage.haskell.org/package/Graph500"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mersenne-random-pure64-0.2:=[profile?] <dev-haskell/mersenne-random-pure64-0.3:=[profile?]
	>=dev-haskell/mtl-1.1:=[profile?]
	>=dev-haskell/random-1.0:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
