# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="CV"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="OpenCV based machine vision library"
HOMEPAGE="http://hackage.haskell.org/package/CV"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.5:=[profile?]
	>=dev-haskell/carray-0.1.5:=[profile?]
	>=dev-haskell/jyu-utils-0.1:=[profile?] <dev-haskell/jyu-utils-0.2:=[profile?]
	>=dev-haskell/mtl-1.1.0:=[profile?]
	>dev-haskell/parallel-1.1:=[profile?]
	>=dev-haskell/quickcheck-2.1:2=[profile?]
	>=dev-haskell/random-1.0.0:=[profile?]
	dev-haskell/storable-complex:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/opencv_calib3d
	unknown-c-lib/opencv_contrib
	unknown-c-lib/opencv_core
	unknown-c-lib/opencv_features2d
	unknown-c-lib/opencv_highgui
	unknown-c-lib/opencv_imgproc
	unknown-c-lib/opencv_legacy
	unknown-c-lib/opencv_ml
	unknown-c-lib/opencv_objdetect
	unknown-c-lib/opencv_video
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
