# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Snusmumrik"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="E-library directory based on FUSE virtual file system"
HOMEPAGE="http://bitbucket.org/jetxee/snusmumrik/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="debug"

RDEPEND="dev-haskell/convertible:=
	dev-haskell/hdbc:2=
	dev-haskell/hdbc-sqlite3:=
	>=dev-haskell/hfuse-0.2.1:=
	dev-haskell/hslogger:=
	dev-haskell/iconv:=
	>=dev-haskell/libzip-0.0.2:= <dev-haskell/libzip-0.1:=
	dev-haskell/regex-tdfa:=
	dev-haskell/stm:=
	dev-haskell/utf8-string:=
	dev-haskell/xml:=
	>=dev-lang/ghc-7.4.1:=
	dev-libs/libzip
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
	dev-haskell/cpphs
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag debug debug)
}
