# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="GPipe-Collada"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Load GPipe meshes from Collada files"
HOMEPAGE="http://www.haskell.org/haskellwiki/GPipe"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/gpipe-1.3.1:=[profile?]
	>=dev-haskell/haxml-1.20:=[profile?] <dev-haskell/haxml-1.21:=[profile?]
	dev-haskell/mtl:=[profile?]
	~dev-haskell/vec-0.9.8:=[profile?]
	~dev-haskell/vec-transform-1.0.5:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
