# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="TimePiece"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A simple tile-based digital clock screen saver"
HOMEPAGE="http://hackage.haskell.org/package/TimePiece"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/old-locale:=
	dev-haskell/old-time:=
	dev-haskell/random:=
	>=dev-haskell/sdl-0.5.4:=
	dev-haskell/sdl-gfx:=
	dev-haskell/sdl-image:=
	dev-haskell/sdl-ttf:=
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/SDLmain
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"
