# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="CMCompare"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Infernal covariance model comparison"
HOMEPAGE="http://www.tbi.univie.ac.at/software/cmcompare/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/biobaseinfernal-0.7:=[profile?] <dev-haskell/biobaseinfernal-0.8:=[profile?]
	>=dev-haskell/biobasexna-0.6.3:=[profile?] <dev-haskell/biobasexna-0.6.4:=[profile?]
	>=dev-haskell/cmdargs-0.10:=[profile?]
	>=dev-haskell/lens-3:=[profile?] <dev-haskell/lens-4:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
