# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="CMCompare"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Infernal covariance model comparison"
HOMEPAGE="http://www.tbi.univie.ac.at/software/cmcompare/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/biobase-0.0.2:= <dev-haskell/biobase-0.0.3:=
	>=dev-haskell/biobaseinfernal-0.0.2:= <dev-haskell/biobaseinfernal-0.0.3:=
	~dev-haskell/cmdargs-0.3:=
	>=dev-haskell/hstools-0.0.1.1:= <dev-haskell/hstools-0.0.2:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4.0
"

S="${WORKDIR}/${MY_P}"
