# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="HGraphStorage"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Graph database stored on disk"
HOMEPAGE="https://github.com/JPMoresmau/HGraphStorage"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/lifted-base:=[profile?]
	>=dev-haskell/monad-control-1.0:=[profile?]
	dev-haskell/monad-logger:=[profile?]
	dev-haskell/resourcet:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/transformers:=[profile?]
	dev-haskell/transformers-base:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( dev-haskell/hunit
		dev-haskell/quickcheck
		>dev-haskell/tasty-0.10
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck )
"

S="${WORKDIR}/${MY_P}"
