# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="GeBoP"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Several games"
HOMEPAGE="http://www.haskell.org/haskellwiki/GeBoP"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/random-1.0:= <dev-haskell/random-1.1:=
	>=dev-haskell/wx-0.11:= <dev-haskell/wx-0.91:=
	>=dev-haskell/wxcore-0.11:= <dev-haskell/wxcore-0.91:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
