# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="LambdaHack"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A roguelike game engine in early and active development"
HOMEPAGE="http://github.com/kosmikus/LambdaHack"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="curses std vty"

RDEPEND=">=dev-haskell/binary-0.5.0.2:=[profile?] <dev-haskell/binary-1:=[profile?]
	>=dev-haskell/configfile-1.1.1:=[profile?] <dev-haskell/configfile-2:=[profile?]
	>=dev-haskell/mtl-2.0.1:=[profile?] <dev-haskell/mtl-3:=[profile?]
	>=dev-haskell/old-time-1.0.0.7:=[profile?] <dev-haskell/old-time-2:=[profile?]
	>=dev-haskell/random-1.0.1:=[profile?] <dev-haskell/random-2:=[profile?]
	>=dev-haskell/zlib-0.5.3.1:=[profile?] <dev-haskell/zlib-1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	curses? ( >=dev-haskell/hscurses-1.4.1:=[profile?] <dev-haskell/hscurses-2:=[profile?] )
	!curses? ( vty? ( >=dev-haskell/vty-4.7.0.6:=[profile?] )
			!vty? ( !std? ( >=dev-haskell/gtk-0.12.1:=[profile?] <dev-haskell/gtk-0.13:=[profile?] ) ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag curses curses) \
		$(cabal_flag std std) \
		$(cabal_flag vty vty)
}
