# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="LambdaHack"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A game engine library for roguelike dungeon crawlers"
HOMEPAGE="http://github.com/LambdaHack/LambdaHack"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="curses +expose_internal vty"

RDEPEND=">=dev-haskell/assert-failure-0.1:=[profile?] <dev-haskell/assert-failure-1:=[profile?]
	>=dev-haskell/async-2:=[profile?] <dev-haskell/async-3:=[profile?]
	>=dev-haskell/binary-0.7:=[profile?] <dev-haskell/binary-1:=[profile?]
	>=dev-haskell/enummapset-th-0.6.0.0:=[profile?] <dev-haskell/enummapset-th-1:=[profile?]
	>=dev-haskell/hashable-1.1.2.5:=[profile?] <dev-haskell/hashable-2:=[profile?]
	>=dev-haskell/hsini-0.2:=[profile?] <dev-haskell/hsini-2:=[profile?]
	>=dev-haskell/keys-3:=[profile?] <dev-haskell/keys-4:=[profile?]
	>=dev-haskell/miniutter-0.4.1:=[profile?] <dev-haskell/miniutter-2:=[profile?]
	>=dev-haskell/mtl-2.0.1:=[profile?] <dev-haskell/mtl-3:=[profile?]
	>=dev-haskell/old-time-1.0.0.7:=[profile?] <dev-haskell/old-time-2:=[profile?]
	>=dev-haskell/pretty-show-1.6:=[profile?] <dev-haskell/pretty-show-2:=[profile?]
	>=dev-haskell/random-1.0.1:=[profile?] <dev-haskell/random-2:=[profile?]
	>=dev-haskell/stm-2.4:=[profile?] <dev-haskell/stm-3:=[profile?]
	>=dev-haskell/text-0.11.2.3:=[profile?] <dev-haskell/text-2:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-1:=[profile?]
	>=dev-haskell/unordered-containers-0.2.3:=[profile?] <dev-haskell/unordered-containers-1:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?] <dev-haskell/vector-1:=[profile?]
	>=dev-haskell/vector-binary-instances-0.2:=[profile?] <dev-haskell/vector-binary-instances-1:=[profile?]
	>=dev-haskell/zlib-0.5.3.1:=[profile?] <dev-haskell/zlib-1:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	curses? ( >=dev-haskell/hscurses-1.4.1:=[profile?] <dev-haskell/hscurses-2:=[profile?] )
	vty? ( !curses? ( >=dev-haskell/vty-4.7.0.6:=[profile?] <dev-haskell/vty-5:=[profile?] ) )
	!vty? ( !curses? ( >=dev-haskell/gtk-0.12.1:=[profile?] <dev-haskell/gtk-0.13:=[profile?]
				unknown-pkg-config/x11
				x11-libs/gtk+:2 ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	!curses? ( !vty? ( virtual/pkgconfig ) )
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag curses curses) \
		$(cabal_flag expose_internal expose_internal) \
		$(cabal_flag vty vty)
}
