# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="LambdaHack"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="a small roguelike game"
HOMEPAGE="http://hackage.haskell.org/package/LambdaHack"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="curses +gtk"

RDEPEND=">=dev-haskell/binary-0.4:=
	>=dev-haskell/mtl-1.1:=
	>=dev-haskell/random-1:=
	>=dev-haskell/zlib-0.4:=
	>=dev-lang/ghc-7.4.1:=
	curses? ( >=dev-haskell/hscurses-1.3:=
			unknown-c-lib/curses )
	!curses? ( gtk? ( >=dev-haskell/gtk-0.9.12:= )
			!gtk? ( >=dev-haskell/vty-3:= ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag curses curses) \
		$(cabal_flag gtk gtk)
}
