# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Performance Tests for the Haskell bindings for Amazon Web Services (AWS)"
HOMEPAGE="http://github.com/alephcloud/hs-aws-performance-tests"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="with-chart"

RDEPEND=">=dev-haskell/aeson-0.7:=[profile?]
	>=dev-haskell/async-2.0:=[profile?]
	>=dev-haskell/aws-0.10.3:=[profile?]
	>=dev-haskell/configuration-tools-0.2.4:=[profile?]
	>=dev-haskell/errors-1.4.7:=[profile?]
	>=dev-haskell/http-client-0.3:=[profile?]
	>=dev-haskell/lens-4.2:=[profile?]
	>=dev-haskell/lifted-base-0.2:=[profile?]
	>=dev-haskell/monad-control-0.3:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?]
	>=dev-haskell/resourcet-1.1:=[profile?]
	>=dev-haskell/statistics-0.12:=[profile?]
	>=dev-haskell/text-1.1:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	with-chart? ( >=dev-haskell/chart-1.2:=[profile?]
			>=dev-haskell/chart-cairo-1.2:=[profile?]
			>=dev-haskell/colour-2.3:=[profile?]
			>=dev-haskell/data-default-0.5:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag with-chart with-chart)
}
