# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="GTALib"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A library for GTA programming"
HOMEPAGE="https://bitbucket.org/emoto/gtalib"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/parallel-3.1:=[profile?] <dev-haskell/parallel-3.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/hunit-1.2.4.2 <dev-haskell/hunit-1.3
		>=dev-haskell/test-framework-0.6 <dev-haskell/test-framework-0.7
		>=dev-haskell/test-framework-hunit-0.2.7 <dev-haskell/test-framework-hunit-0.3 )
"

S="${WORKDIR}/${MY_P}"
