# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HStringTemplateHelpers"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Convenience functions and instances for HStringTemplate"
HOMEPAGE="http://hackage.haskell.org/package/HStringTemplateHelpers"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/hsh:=[profile?]
	dev-haskell/hstringtemplate:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/strict:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"
