# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="INblobs"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Editor and interpreter for Interaction Nets"
HOMEPAGE="http://haskell.di.uminho.pt/jmvilaca/INblobs/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/haxml-1.19:=
	dev-haskell/polyparse:=
	>=dev-haskell/wx-0.9:=
	>=dev-haskell/wxcore-0.9:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
