# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="MagicHaskeller"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Automatic inductive functional programmer by systematic search"
HOMEPAGE="http://nautilus.cs.miyazaki-u.ac.jp/~skata/MagicHaskeller.html"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+ghc7 +ghcapi +readfile"

RDEPEND="dev-haskell/mtl:=[profile?]
	dev-haskell/random:=[profile?]
	dev-haskell/syb:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	ghc7? ( >=dev-haskell/ghc-7:=[profile?] )
	ghcapi? ( dev-haskell/ghc-paths:=[profile?]
			dev-haskell/old-time:=[profile?]
			!ghc7? ( >=dev-haskell/ghc-6.10:=[profile?] ) )
	readfile? ( dev-haskell/haskell-src:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag ghc7 ghc7) \
		$(cabal_flag ghcapi ghcapi) \
		$(cabal_flag readfile readfile)
}
