# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Haskell bindings for AWS Lambda"
HOMEPAGE="https://github.com/alephcloud/hs-aws-lambda"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.8.0.2:=[profile?]
	>=dev-haskell/aws-general-0.1:=[profile?]
	dev-haskell/base-unicode-symbols:=[profile?]
	>=dev-haskell/exceptions-0.6.1:=[profile?]
	>=dev-haskell/http-client-0.4.6:=[profile?]
	>=dev-haskell/http-types-0.8.5:=[profile?]
	>=dev-haskell/lens-4.7:=[profile?]
	>=dev-haskell/lens-action-0.1.0.1:=[profile?]
	>=dev-haskell/lens-aeson-1.0.0.3:=[profile?]
	>=dev-haskell/mtl-2.1.3.1:=[profile?]
	>=dev-haskell/old-locale-1.0.0.6:=[profile?]
	>=dev-haskell/text-1.2.0.0:=[profile?]
	>=dev-haskell/wreq-0.3.0.1:=[profile?]
	>=dev-haskell/zip-archive-0.2.3.5:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
