# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Relational Algebra and SQL Code Generation"
HOMEPAGE="http://hackage.haskell.org/package/algebra-sql"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.8:=[profile?]
	>=dev-haskell/algebra-dag-0.1:=[profile?]
	>=dev-haskell/ansi-wl-pprint-0.6:=[profile?]
	>=dev-haskell/dlist-0.7:=[profile?]
	>=dev-haskell/errors-1.0:=[profile?]
	>=dev-haskell/fgl-5.5:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?]
	>=dev-haskell/multiset-0.2:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
