# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="CSPM-cspm"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="cspm command line tool for analyzing CSPM specifications"
HOMEPAGE="http://hackage.haskell.org/package/CSPM-cspm"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cmdargs-0.10:=[profile?] <dev-haskell/cmdargs-0.11:=[profile?]
	>=dev-haskell/cspm-corelanguage-0.3:=[profile?] <dev-haskell/cspm-corelanguage-0.4:=[profile?]
	>=dev-haskell/cspm-firingrules-0.4:=[profile?] <dev-haskell/cspm-firingrules-0.5:=[profile?]
	>=dev-haskell/cspm-frontend-0.9:=[profile?] <dev-haskell/cspm-frontend-0.10:=[profile?]
	>=dev-haskell/cspm-interpreter-0.6:=[profile?] <dev-haskell/cspm-interpreter-0.7:=[profile?]
	>=dev-haskell/cspm-toprolog-0.5:=[profile?] <dev-haskell/cspm-toprolog-0.6:=[profile?]
	~dev-haskell/hslua-0.3.6:=[profile?]
	>=dev-haskell/parallel-3.2:=[profile?] <dev-haskell/parallel-3.3:=[profile?]
	>=dev-haskell/prettyclass-1.0:=[profile?] <dev-haskell/prettyclass-1.1:=[profile?]
	>=dev-haskell/syb-0.4:=[profile?] <dev-haskell/syb-0.5:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-haskell/xml-1.3:=[profile?] <dev-haskell/xml-1.4:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
