# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="PortFusion"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="high-performance distributed reverse / forward proxy & tunneling for TCP"
HOMEPAGE="http://fusion.corsis.eu"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="llvm static"

RDEPEND="dev-haskell/network:=
	dev-haskell/splice:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag llvm llvm) \
		$(cabal_flag static static)
}
