# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="HaTeX-meta"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="HaTeX monad modules builder"
HOMEPAGE="http://dhelta.net/hprojects/HaTeX-meta"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/ghc-7:= <dev-haskell/ghc-8:=
	>=dev-haskell/haddock-2.9:= <dev-haskell/haddock-2.10:=
	>=dev-haskell/haskell-src-exts-1.11:= <dev-haskell/haskell-src-exts-1.12:=
	>=dev-haskell/mtl-2:= <dev-haskell/mtl-3:=
	>=dev-haskell/parsec-3:= <dev-haskell/parsec-4:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
