# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Low level bindings to the C levmar (Levenberg-Marquardt) library"
HOMEPAGE="https://github.com/basvandijk/bindings-levmar"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="accelerate mkl"

RDEPEND=">=dev-haskell/bindings-dsl-1.0.15:=[profile?] <dev-haskell/bindings-dsl-1.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	mkl? ( sci-libs/mkl )
	!mkl? ( unknown-c-lib/blas
		unknown-c-lib/lapack )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag accelerate accelerate) \
		$(cabal_flag mkl mkl)
}
