# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Authentication methods for Haskell web applications"
HOMEPAGE="http://github.com/snoyberg/authenticate/tree/master"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+transformers_02"

RDEPEND=">=dev-haskell/failure-0.0.0:=[profile?] <dev-haskell/failure-0.1:=[profile?]
	>=dev-haskell/http-wget-0.6:=[profile?] <dev-haskell/http-wget-0.7:=[profile?]
	>=dev-haskell/json-0.4.3:=[profile?] <dev-haskell/json-0.5:=[profile?]
	>=dev-haskell/safe-failure-0.4:=[profile?] <dev-haskell/safe-failure-0.5:=[profile?]
	dev-haskell/syb:=[profile?]
	>=dev-haskell/tagsoup-0.6:=[profile?] <dev-haskell/tagsoup-0.9:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	transformers_02? ( >=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.3:=[profile?] )
	!transformers_02? ( >=dev-haskell/transformers-0.1:=[profile?] <dev-haskell/transformers-0.2:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag transformers_02 transformers_02)
}
