# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Authentication methods for Haskell web applications"
HOMEPAGE="http://github.com/snoyberg/authenticate/tree/master"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.3.2.11:=[profile?]
	>=dev-haskell/attoparsec-0.9:=[profile?]
	>=dev-haskell/base64-bytestring-0.1:=[profile?] <dev-haskell/base64-bytestring-0.2:=[profile?]
	>=dev-haskell/blaze-builder-0.2:=[profile?] <dev-haskell/blaze-builder-0.4:=[profile?]
	>=dev-haskell/case-insensitive-0.2:=[profile?]
	>=dev-haskell/enumerator-0.4.7:=[profile?] <dev-haskell/enumerator-0.5:=[profile?]
	>=dev-haskell/failure-0.0.0:=[profile?] <dev-haskell/failure-0.2:=[profile?]
	>=dev-haskell/http-enumerator-0.6.5.4:=[profile?] <dev-haskell/http-enumerator-0.8:=[profile?]
	>=dev-haskell/http-types-0.6:=[profile?] <dev-haskell/http-types-0.7:=[profile?]
	>=dev-haskell/network-2.2.1:=[profile?] <dev-haskell/network-2.4:=[profile?]
	>=dev-haskell/random-1.0:=[profile?] <dev-haskell/random-1.1:=[profile?]
	>=dev-haskell/rsa-1.0:=[profile?] <dev-haskell/rsa-1.1:=[profile?]
	>=dev-haskell/sha-1.4:=[profile?] <dev-haskell/sha-1.6:=[profile?]
	>=dev-haskell/tagsoup-0.12:=[profile?] <dev-haskell/tagsoup-0.13:=[profile?]
	>=dev-haskell/text-0.5:=[profile?] <dev-haskell/text-1.0:=[profile?]
	>=dev-haskell/tls-0.7:=[profile?] <dev-haskell/tls-0.9:=[profile?]
	>=dev-haskell/transformers-0.1:=[profile?] <dev-haskell/transformers-0.3:=[profile?]
	>=dev-haskell/xml-enumerator-0.4:=[profile?] <dev-haskell/xml-enumerator-0.5:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
