# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Constructive abstract algebra"
HOMEPAGE="http://github.com/ekmett/algebra/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/categories-0.59:=[profile?] <dev-haskell/categories-0.60:=[profile?]
	>=dev-haskell/distributive-0.2:=[profile?] <dev-haskell/distributive-0.3:=[profile?]
	>=dev-haskell/keys-2.1.2:=[profile?] <dev-haskell/keys-2.2:=[profile?]
	>=dev-haskell/mtl-2:=[profile?] <dev-haskell/mtl-2.1:=[profile?]
	>=dev-haskell/representable-functors-2.1.2:=[profile?] <dev-haskell/representable-functors-2.2:=[profile?]
	>=dev-haskell/representable-tries-2.0.4:=[profile?] <dev-haskell/representable-tries-2.1:=[profile?]
	>=dev-haskell/semigroupoids-1.2.6.1:=[profile?] <dev-haskell/semigroupoids-1.3:=[profile?]
	>=dev-haskell/semigroups-0.8:=[profile?] <dev-haskell/semigroups-0.9:=[profile?]
	>=dev-haskell/tagged-0.2.2.3:=[profile?] <dev-haskell/tagged-0.3:=[profile?]
	>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.3:=[profile?]
	>=dev-haskell/void-0.5.4.3:=[profile?] <dev-haskell/void-0.6:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
