# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Toolsuite for automated design of business processes"
HOMEPAGE="ampersand.sourceforge.net"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+executable +library"

RDEPEND=">=dev-haskell/graphviz-2999.16.0.0:=[profile?] <=dev-haskell/graphviz-2999.17:=[profile?]
	>=dev-haskell/hashable-1.2:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/mtl-2.1.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/old-locale-1.0.0.4:=[profile?] <dev-haskell/old-locale-1.1:=[profile?]
	>=dev-haskell/pandoc-1.12.1:=[profile?] <dev-haskell/pandoc-1.13:=[profile?]
	>=dev-haskell/pandoc-types-1.12.3:=[profile?] <dev-haskell/pandoc-types-1.13:=[profile?]
	>=dev-haskell/split-0.1:=[profile?] <dev-haskell/split-0.2:=[profile?]
	>=dev-haskell/spreadsheetml-0.1:=[profile?] <dev-haskell/spreadsheetml-0.2:=[profile?]
	>=dev-haskell/utf8-string-0.3.7:=[profile?] <dev-haskell/utf8-string-0.4:=[profile?]
	>=dev-lang/ghc-7.6.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag executable executable) \
		$(cabal_flag library library)
}
