# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Haskell bindings for Amazon DynamoDB Streams"
HOMEPAGE="http://hackage.haskell.org/package/aws-dynamodb-streams"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.8.0.0:=[profile?]
	>=dev-haskell/attoparsec-0.12.0.0:=[profile?]
	>=dev-haskell/aws-0.10.5:=[profile?]
	>=dev-haskell/aws-general-0.1:=[profile?]
	dev-haskell/base-unicode-symbols:=[profile?]
	>=dev-haskell/base16-bytestring-0.1.1.6:=[profile?]
	>=dev-haskell/base64-bytestring-1.0.0.0:=[profile?]
	>=dev-haskell/byteable-0.1.1:=[profile?]
	>=dev-haskell/case-insensitive-1.2.0.0:=[profile?]
	>=dev-haskell/conduit-1.2.0:=[profile?]
	>=dev-haskell/conduit-extra-1.1.4:=[profile?]
	>=dev-haskell/cryptohash-0.11.6:=[profile?]
	>=dev-haskell/http-conduit-2.1.5:=[profile?]
	>=dev-haskell/http-types-0.0.8.5:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?]
	>=dev-haskell/old-locale-1.0.0.0:=[profile?]
	>=dev-haskell/parsers-0.11:=[profile?]
	>=dev-haskell/profunctors-4.2:=[profile?]
	>=dev-haskell/resourcet-1.1.3:=[profile?]
	>=dev-haskell/scientific-0.3.3.2:=[profile?]
	>=dev-haskell/text-1.2.0.0:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
