# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="A modern tiling window manager with a gentle learning curve"
HOMEPAGE="http://www.bluetile.org/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/glade:=
	dev-haskell/gtk:=
	dev-haskell/random:=
	dev-haskell/utf8-string:=
	>=dev-haskell/x11-1.4:=
	>=dev-haskell/xmonad-0.9.1:=
	>=dev-haskell/xmonad-contrib-0.9.1:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"
