# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="PTQ"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An implementation of Montague's PTQ"
HOMEPAGE="http://msakai.jp/hiki/?hsPTQ"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+network-uri +utf8cgi utf8terminal"

RDEPEND="dev-haskell/mtl:=
	dev-haskell/xml:=
	>=dev-lang/ghc-7.4.1:=
	network-uri? ( >=dev-haskell/network-2.6:=
			>=dev-haskell/network-uri-2.6:= )
	!network-uri? ( <dev-haskell/network-2.6:=
			<dev-haskell/network-uri-2.6:= )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag network-uri network-uri) \
		$(cabal_flag utf8cgi utf8cgi) \
		$(cabal_flag utf8terminal utf8terminal)
}
