# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="WxGeneric"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Generic (SYB3) construction of wxHaskell widgets"
HOMEPAGE="http://www.haskell.org/haskellwiki/WxGeneric"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-2.0.0.0:=[profile?]
	>=dev-haskell/sybwidget-0.5.5:=[profile?] <dev-haskell/sybwidget-0.6.0:=[profile?]
	>=dev-haskell/wx-0.12.0:=[profile?]
	>=dev-haskell/wxcore-0.12.0:=[profile?]
	>=dev-haskell/xtc-1.0:=[profile?] <dev-haskell/xtc-1.1.0:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"
