# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="SimpleLog"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Simple, configurable logging"
HOMEPAGE="https://github.com/exFalso/SimpleLog/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="<dev-haskell/ansi-terminal-1:=[profile?]
	<dev-haskell/attoparsec-1:=[profile?]
	<dev-haskell/forkablet-1:=[profile?]
	>=dev-haskell/monad-control-1:=[profile?] <dev-haskell/monad-control-2:=[profile?]
	>=dev-haskell/mtl-2:=[profile?] <dev-haskell/mtl-3:=[profile?]
	>=dev-haskell/old-locale-1:=[profile?] <dev-haskell/old-locale-2:=[profile?]
	>=dev-haskell/resourcet-1:=[profile?] <dev-haskell/resourcet-2:=[profile?]
	<dev-haskell/semigroups-1:=[profile?]
	>=dev-haskell/stm-2:=[profile?] <dev-haskell/stm-3:=[profile?]
	>=dev-haskell/text-1:=[profile?] <dev-haskell/text-2:=[profile?]
	<dev-haskell/th-lift-1:=[profile?]
	<dev-haskell/transformers-1:=[profile?]
	<dev-haskell/transformers-base-1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
