# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Automatic Rule-Based Time Tracker"
HOMEPAGE="http://www.joachim-breitner.de/projects#arbtt"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=
	dev-haskell/bytestring-progress:=
	dev-haskell/old-locale:=
	>=dev-haskell/parsec-3:= <dev-haskell/parsec-4:=
	dev-haskell/pcre-light:=
	dev-haskell/strict:=
	dev-haskell/terminal-progress-bar:=
	dev-haskell/transformers:=
	dev-haskell/utf8-string:=
	>dev-haskell/x11-1.4.4:=
	>=dev-lang/ghc-7.4.1:=
	x11-libs/libXScrnSaver
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
