# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="BlogLiterately-diagrams"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Include images in blog posts with inline diagrams code"
HOMEPAGE="http://hackage.haskell.org/package/BlogLiterately-diagrams"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/blogliterately-0.6:=[profile?] <dev-haskell/blogliterately-0.7:=[profile?]
	>=dev-haskell/diagrams-builder-0.2:=[profile?] <dev-haskell/diagrams-builder-0.5:=[profile?]
	>=dev-haskell/diagrams-cairo-0.6:=[profile?] <dev-haskell/diagrams-cairo-0.7:=[profile?]
	>=dev-haskell/diagrams-lib-0.6:=[profile?] <dev-haskell/diagrams-lib-0.7:=[profile?]
	>=dev-haskell/pandoc-1.9:=[profile?] <dev-haskell/pandoc-1.12:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?] <dev-haskell/safe-0.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"

S="${WORKDIR}/${MY_P}"
