# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="GrammarProducts"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Grammar products and higher-dimensional grammars"
HOMEPAGE="http://www.tbi.univie.ac.at/~choener/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/adpfusion-0.2.0:=[profile?]
	dev-haskell/ansi-wl-pprint:=[profile?]
	>=dev-haskell/cmdargs-0.10:=[profile?] <dev-haskell/cmdargs-0.11:=[profile?]
	dev-haskell/data-default:=[profile?]
	>=dev-haskell/formalgrammars-0.0.0.1:=[profile?]
	dev-haskell/hatex:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/newtype:=[profile?]
	dev-haskell/parsers:=[profile?]
	>=dev-haskell/primitivearray-0.5.1.0:=[profile?]
	dev-haskell/semigroups:=[profile?]
	dev-haskell/transformers:=[profile?]
	dev-haskell/trifecta:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6.0
"

S="${WORKDIR}/${MY_P}"
