# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Network-NineP"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="High-level abstraction over 9P protocol"
HOMEPAGE="http://hackage.haskell.org/package/Network-NineP"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.5.1.0:=[profile?] <dev-haskell/binary-0.8:=[profile?]
	>=dev-haskell/convertible-1.0.11.1:=[profile?] <dev-haskell/convertible-1.2:=[profile?]
	>=dev-haskell/monad-loops-0.3.3.0:=[profile?] <dev-haskell/monad-loops-0.5:=[profile?]
	>=dev-haskell/mstate-0.2.4:=[profile?] <dev-haskell/mstate-0.3:=[profile?]
	>=dev-haskell/mtl-2.1.2:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/network-2.3.0.14:=[profile?] <dev-haskell/network-2.6:=[profile?]
	>=dev-haskell/ninep-0.0.2:=[profile?] <dev-haskell/ninep-0.1:=[profile?]
	>=dev-haskell/regex-posix-0.95.2:=[profile?] <dev-haskell/regex-posix-0.96:=[profile?]
	>=dev-haskell/stateref-0.3:=[profile?] <dev-haskell/stateref-0.4:=[profile?]
	>=dev-haskell/transformers-0.3.0.0:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
