# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="MuCheck-SmallCheck"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Automated Mutation Testing for SmallCheck tests"
HOMEPAGE="https://bitbucket.com/osu-testing/mucheck-smallcheck"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mucheck-0.2.0:=[profile?] <dev-haskell/mucheck-0.2.1:=[profile?]
	~dev-haskell/smallcheck-1.1.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"

S="${WORKDIR}/${MY_P}"
