# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="OpenVG"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="OpenVG (shivag-0.2.1) binding"
HOMEPAGE="http://code.google.com/p/copperbox/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/glut-2.1.1.2:=[profile?] <dev-haskell/glut-2.2:=[profile?]
	>=dev-haskell/opengl-2.2:=[profile?] <dev-haskell/opengl-2.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
