# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Hoed"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Lighweight algorithmic debugging based on observing intermediate values and the cost centre stack"
HOMEPAGE="http://maartenfaddegon.nl"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="buildexamples validate"

RDEPEND="~dev-haskell/libgraph-1.4:=[profile?]
	dev-haskell/mtl:=[profile?]
	~dev-haskell/rbtree-0.0.5:=[profile?]
	dev-haskell/regex-posix:=[profile?]
	dev-haskell/threepenny-gui:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	buildexamples? ( dev-haskell/network:=[profile?] )
	validate? ( dev-haskell/network:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag buildexamples buildexamples) \
		$(cabal_flag validate validate)
}
