# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Boolean normal form: NNF, DNF & CNF"
HOMEPAGE="http://hackage.haskell.org/package/boolean-normal-forms"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cond-0.4.1:=[profile?] <dev-haskell/cond-0.5:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/quickcheck-2.7 <=dev-haskell/quickcheck-2.8
		>=dev-haskell/tasty-0.8
		>=dev-haskell/tasty-quickcheck-0.8.0.3 )
"
