# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="LambdaPrettyQuote"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Parser, pretty printer, quasiquoter, and Arbitrary helpers for the untyped lambda calculus"
HOMEPAGE="http://github.com/jfischoff/LambdaPrettyQuote"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/debugtracehelpers-0.12:=[profile?]
	>=dev-haskell/hunit-1.2.4.2:=[profile?]
	>=dev-haskell/lambda-ast-0.0.4:=[profile?]
	>=dev-haskell/parsec-3.1.2:=[profile?]
	>=dev-haskell/quickcheck-2.4.1.1:2=[profile?]
	>=dev-haskell/syb-0.3.5:=[profile?]
	>=dev-haskell/test-framework-0.4.1.1:=[profile?]
	>=dev-haskell/test-framework-hunit-0.2.7:=[profile?]
	>=dev-haskell/test-framework-quickcheck2-0.2.10:=[profile?]
	>=dev-haskell/transformers-0.2.2.0:=[profile?]
	>=dev-haskell/uniplate-1.6.5:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/th-instances-0.1.0.2 )
"

S="${WORKDIR}/${MY_P}"
