# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="GlomeView"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="SDL Frontend for Glome ray tracer"
HOMEPAGE="http://haskell.org/haskellwiki/Glome"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/glometrace:=
	dev-haskell/glomevec:=
	dev-haskell/monad-par:=
	dev-haskell/random:=
	dev-haskell/sdl:=
	dev-haskell/vector:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2.3
"

S="${WORKDIR}/${MY_P}"
