# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Hs2lib"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Library and Preprocessor that makes it easier to create shared libs from Haskell programs"
HOMEPAGE="http://blog.zhox.com/category/hs2lib/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cereal-0.3.0.0:=[profile?]
	>=dev-haskell/ghc-paths-0.1.0.5:=[profile?]
	>=dev-haskell/haddock-2.7.2:=[profile?]
	~dev-haskell/haskell-src-exts-1.13.5:=[profile?]
	>=dev-haskell/mtl-1.1.0.2:=[profile?]
	>=dev-haskell/old-locale-1.0.0.2:=[profile?]
	>=dev-haskell/quickcheck-2.1.0.1:2=[profile?]
	>=dev-haskell/random-1.0.0.1:=[profile?]
	>=dev-haskell/syb-0.1.0.2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	|| ( ( >=dev-haskell/ghc-6.12:=[profile?] <dev-haskell/ghc-7.0:=[profile?] )
		>=dev-haskell/ghc-7.0.2:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	dev-haskell/cpphs
"

S="${WORKDIR}/${MY_P}"
