# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Plot-ho-matic"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Real-time line plotter for protobuf-like data"
HOMEPAGE="http://hackage.haskell.org/package/Plot-ho-matic"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="examples"

RDEPEND=">=dev-haskell/chart-1.1:=[profile?]
	>=dev-haskell/chart-gtk-1.1:=[profile?]
	dev-haskell/data-default-class:=[profile?]
	dev-haskell/glib:=[profile?]
	dev-haskell/gtk:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/linear:=[profile?]
	dev-haskell/stm:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag examples examples)
}
