# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Configger"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Parse config files"
HOMEPAGE="http://hackage.haskell.org/package/Configger"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/dangerous-0.2.2:=[profile?]
	>=dev-haskell/missingh-1.0:=[profile?]
	>=dev-haskell/mtl-1.1:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
