# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Convert adblock config files to privoxy format"
HOMEPAGE="https://projects.zubr.me/wiki/adblock2privoxy"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cabal-1.6:= <dev-haskell/cabal-1.20:=
	dev-haskell/http-conduit:=
	dev-haskell/missingh:=
	dev-haskell/mtl:=
	>=dev-haskell/network-2.4:= <dev-haskell/network-2.6:=
	>=dev-haskell/old-locale-1.0:= <dev-haskell/old-locale-1.1:=
	dev-haskell/pandoc:=
	>=dev-haskell/pandoc-types-1.12.3:= <dev-haskell/pandoc-types-1.13:=
	dev-haskell/parsec:=
	dev-haskell/parsec-permutation:=
	>=dev-haskell/strict-0.3:= <dev-haskell/strict-0.4:=
	>=dev-haskell/text-0.11:= <dev-haskell/text-0.12:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
