# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="RPM package builder for Haskell Cabal source packages"
HOMEPAGE="http://www.serpentine.com/software/cabal-rpm/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+splitbase"

RDEPEND="dev-haskell/cabal:=
	>=dev-lang/ghc-7.4.1:=
	splitbase? ( dev-haskell/old-locale:= )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag splitbase splitbase)
}
