# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="X11-xfixes"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A binding to the Xfixes X11 extension library"
HOMEPAGE="https://github.com/reacocard/x11-xfixes"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/x11:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/Xfixes
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4
"

S="${WORKDIR}/${MY_P}"
