# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A backend agnostic, concurrent BTree"
HOMEPAGE="https://github.com/brinchj/btree-concurrent"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/base16-bytestring-0.1:=[profile?] <dev-haskell/base16-bytestring-0.2:=[profile?]
	>=dev-haskell/base64-bytestring-0.1:=[profile?] <dev-haskell/base64-bytestring-0.2:=[profile?]
	>=dev-haskell/cereal-0.3:=[profile?] <dev-haskell/cereal-0.4:=[profile?]
	>=dev-haskell/cprng-aes-0.2:=[profile?] <dev-haskell/cprng-aes-0.3:=[profile?]
	>=dev-haskell/entropy-0.2:=[profile?]
	>=dev-haskell/hashable-1:=[profile?] <dev-haskell/hashable-2:=[profile?]
	>=dev-haskell/mtl-2:=[profile?] <dev-haskell/mtl-3:=[profile?]
	>=dev-haskell/old-time-1:=[profile?] <dev-haskell/old-time-2:=[profile?]
	>=dev-haskell/random-1:=[profile?] <dev-haskell/random-2:=[profile?]
	>=dev-haskell/snappy-0.2:=[profile?] <dev-haskell/snappy-0.3:=[profile?]
	>=dev-haskell/stm-2.2:=[profile?] <dev-haskell/stm-2.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/quickcheck-2.4 <dev-haskell/quickcheck-2.5 )
"
