# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="OpenGLRaw21"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="The intersection of OpenGL 2.1 and OpenGL 3.1 Core"
HOMEPAGE="http://hackage.haskell.org/package/OpenGLRaw21"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.4.1:=
	|| ( ( >=dev-haskell/openglraw-1.1:=[profile?] <dev-haskell/openglraw-1.2:=[profile?] )
		( >=dev-haskell/openglraw-1.2:=[profile?] <dev-haskell/openglraw-1.3:=[profile?] ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
