# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Parsing and rendering of Stockholm files (used by Pfam, Rfam and Infernal)"
HOMEPAGE="http://hackage.haskell.org/package/biostockholm"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/attoparsec-0.10:=[profile?] <dev-haskell/attoparsec-0.11:=[profile?]
	>=dev-haskell/attoparsec-conduit-0.4:=[profile?] <dev-haskell/attoparsec-conduit-0.5:=[profile?]
	>=dev-haskell/biocore-0.1:=[profile?] <dev-haskell/biocore-0.3:=[profile?]
	>=dev-haskell/blaze-builder-0.3:=[profile?] <dev-haskell/blaze-builder-0.4:=[profile?]
	>=dev-haskell/blaze-builder-conduit-0.4:=[profile?] <dev-haskell/blaze-builder-conduit-0.5:=[profile?]
	>=dev-haskell/conduit-0.4:=[profile?] <dev-haskell/conduit-0.5:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/hspec-0.9 <dev-haskell/hspec-0.10
		dev-haskell/hunit
		dev-haskell/quickcheck
		>=dev-haskell/transformers-0.2
		dev-haskell/zlib-conduit )
"
