# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Gamgine"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Some kind of game library or set of utilities"
HOMEPAGE="http://hackage.haskell.org/package/Gamgine"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/composition-1.0.1.0:=[profile?] <dev-haskell/composition-1.1:=[profile?]
	>=dev-haskell/cpphs-1.18.4:=[profile?] <dev-haskell/cpphs-1.19:=[profile?]
	>=dev-haskell/data-lens-2.10.4:=[profile?] <dev-haskell/data-lens-2.11:=[profile?]
	>=dev-haskell/glfw-b-1.0:=[profile?] <dev-haskell/glfw-b-1.5:=[profile?]
	>=dev-haskell/listzipper-1.2.0.2:=[profile?] <dev-haskell/listzipper-1.3:=[profile?]
	>=dev-haskell/mtl-2.1.3.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/openglraw-1.4.0.0:=[profile?] <dev-haskell/openglraw-1.6:=[profile?]
	>=dev-haskell/parsec-3.1.5:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-haskell/pretty-show-1.6.7:=[profile?] <dev-haskell/pretty-show-1.7:=[profile?]
	>=dev-haskell/statevar-1.0.0.0:=[profile?] <dev-haskell/statevar-1.1:=[profile?]
	>=dev-haskell/unordered-containers-0.2.4.0:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-haskell/utility-ht-0.0.10:=[profile?] <dev-haskell/utility-ht-0.1:=[profile?]
	>=dev-haskell/vec-1.0.1:=[profile?] <dev-haskell/vec-1.1:=[profile?]
	>=dev-haskell/zlib-0.5.4.1:=[profile?] <dev-haskell/zlib-0.6:=[profile?]
	>=dev-lang/ghc-7.6.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
