# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Bidirectionalization for Free! (POPL'09)"
HOMEPAGE="http://hackage.haskell.org/package/bff"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="binaries render stats"

RDEPEND=">=dev-haskell/bimap-0.2.3:=[profile?]
	>=dev-haskell/category-extras-0.53.5:=[profile?]
	~dev-haskell/derive-0.1.1:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	binaries? ( dev-haskell/cgi:=[profile?]
			>=dev-haskell/hint-0.3.2:=[profile?]
			dev-haskell/utf8-string:=[profile?]
			dev-haskell/xhtml:=[profile?] )
	render? ( >=dev-haskell/chart-0.12:=[profile?]
			dev-haskell/colour:=[profile?]
			dev-haskell/data-accessor:=[profile?] )
	stats? ( >=dev-haskell/benchpress-0.2.2.2:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag binaries binaries) \
		$(cabal_flag render render) \
		$(cabal_flag stats stats)
}
