# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Pup-Events-Demo"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A networked event handling framework for hooking into other programs"
HOMEPAGE="http://hackage.haskell.org/package/Pup-Events-Demo"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/glut:=
	dev-haskell/opengl:=
	>=dev-haskell/parsec-3.1.1:=
	dev-haskell/pup-events-client:=
	dev-haskell/pup-events-pqueue:=
	dev-haskell/pup-events-server:=
	>=dev-haskell/stm-2.2:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10.2.0
"

S="${WORKDIR}/${MY_P}"
