# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Process management and supervision daemon"
HOMEPAGE="http://github.com/jamwt/Angel"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/configurator-0.1:=
	dev-haskell/missingh:=
	dev-haskell/mtl:=
	dev-haskell/old-locale:=
	dev-haskell/old-time:=
	>=dev-haskell/stm-2.0:=
	>=dev-haskell/text-0.11:=
	>=dev-haskell/unordered-containers-0.1.4:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
