# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="MiniAgda"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A toy dependently typed programming language with type-based termination"
HOMEPAGE="http://www.tcs.ifi.lmu.de/~abel/miniagda/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/haskell-src-exts-1.14:= <dev-haskell/haskell-src-exts-1.16:=
	>=dev-haskell/mtl-2.2.0.1:= <dev-haskell/mtl-2.3:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/alex
	>=dev-haskell/cabal-1.8
	dev-haskell/happy
"

S="${WORKDIR}/${MY_P}"
