# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A highlight middleware"
HOMEPAGE="http://github.com/nfjinjing/bamboo-plugin-highlight/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bamboo-2009.6.9:=[profile?]
	>=dev-haskell/hack-2009.5.19:=[profile?]
	>=dev-haskell/hack-contrib-2009.6.9:=[profile?]
	dev-haskell/highlighting-kate:=[profile?]
	dev-haskell/hxt:=[profile?]
	>=dev-haskell/mps-2009.5.13:=[profile?]
	dev-haskell/xhtml:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"
