# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="eventsource support for apiary web framework"
HOMEPAGE="https://github.com/philopon/apiary"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="wai2apiary"

RDEPEND=">=dev-haskell/apiary-0.11.3:=[profile?] <dev-haskell/apiary-0.13:=[profile?]
	>=dev-haskell/blaze-builder-0.3:=[profile?] <dev-haskell/blaze-builder-0.4:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	wai2apiary? ( >=dev-haskell/conduit-1.1:=[profile?] <dev-haskell/conduit-1.2:=[profile?]
			>=dev-haskell/wai-eventsource-2.0:=[profile?] <dev-haskell/wai-eventsource-3.0:=[profile?] )
	!wai2apiary? ( >=dev-haskell/wai-extra-3.0:=[profile?] <dev-haskell/wai-extra-3.1:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag wai2apiary wai2apiary)
}
