# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="RNAFoldProgs"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="RNA secondary structure folding"
HOMEPAGE="http://hackage.haskell.org/package/RNAFoldProgs"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/biobase-0.0.2:= <dev-haskell/biobase-0.0.3:=
	>=dev-haskell/biobaseturner-0.0.2.1:= <dev-haskell/biobaseturner-0.0.3:=
	>=dev-haskell/biobasetypes-0.0.2.1:= <dev-haskell/biobasetypes-0.0.3:=
	>=dev-haskell/biobasevienna-0.0.2:= <dev-haskell/biobasevienna-0.0.3:=
	~dev-haskell/cmdargs-0.6:=
	>=dev-haskell/hstools-0.0.1.1:=
	>=dev-haskell/primitive-0.3:= <dev-haskell/primitive-0.4:=
	>=dev-haskell/primitivearray-0.0.2:= <dev-haskell/primitivearray-0.0.3:=
	>=dev-haskell/rnafold-0.0.2:= <dev-haskell/rnafold-0.0.3:=
	>=dev-haskell/split-0.0.2.1:=
	>=dev-haskell/vector-0.7:= <dev-haskell/vector-0.8:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4.0
"

S="${WORKDIR}/${MY_P}"
