# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="tiny library for encoding json"
HOMEPAGE="https://github.com/philopon/blaze-json"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bytestring-builder-0.10:=[profile?] <dev-haskell/bytestring-builder-0.11:=[profile?]
	>=dev-haskell/data-default-class-0.0:=[profile?] <dev-haskell/data-default-class-0.1:=[profile?]
	>=dev-haskell/text-1.1:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/aeson-0.7 <dev-haskell/aeson-0.9
		>=dev-haskell/doctest-0.9 <dev-haskell/doctest-0.10
		>=dev-haskell/quickcheck-2.7 <dev-haskell/quickcheck-2.9
		>=dev-haskell/scientific-0.3 <dev-haskell/scientific-0.4
		>=dev-haskell/tasty-0.10 <dev-haskell/tasty-0.11
		>=dev-haskell/tasty-quickcheck-0.8 <dev-haskell/tasty-quickcheck-0.9
		>=dev-haskell/unordered-containers-0.2 <dev-haskell/unordered-containers-0.3
		>=dev-haskell/vector-0.10 <dev-haskell/vector-0.11 )
"
