# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A highly dynamic, extremely simple, very fun programming language"
HOMEPAGE="http://atomo-lang.org/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+lib"

RDEPEND="~dev-haskell/hashable-1.0.0:=[profile?]
	dev-haskell/haskeline:=[profile?]
	>=dev-haskell/hint-0.3.3.2:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/parsec-3.0.0:=[profile?]
	dev-haskell/regex-pcre:=[profile?]
	>=dev-haskell/text-0.11.0.0:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag lib lib)
}
