# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin test-suite"
inherit haskell-cabal

MY_PN="Bookshelf"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A simple document organizer with some wiki functionality"
HOMEPAGE="http://www.cse.chalmers.se/~emax/bookshelf/Manual.shelf.html"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/citeproc-hs:=
	>=dev-haskell/pandoc-1.10:=
	>=dev-haskell/pandoc-types-1.10:=
	dev-haskell/parseargs:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
