# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Haggressive"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Aggression analysis for Tweets on Twitter"
HOMEPAGE="http://github.io/pold87/Haggressive"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/cabal:=[profile?]
	dev-haskell/cassava:=[profile?]
	dev-haskell/hunit:=[profile?]
	dev-haskell/psqueue:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/tokenize:=[profile?]
	dev-haskell/tuple:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

S="${WORKDIR}/${MY_P}"
