# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A simple library for accessing Azure blob storage"
HOMEPAGE="http://arnovanlumig.com/azure"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="library-only no-hxt"

RDEPEND=">=dev-haskell/base64-bytestring-0.1.2.0:=[profile?]
	>=dev-haskell/case-insensitive-0.4.0.1:=[profile?]
	>=dev-haskell/cmdargs-0.10:=[profile?]
	>=dev-haskell/conduit-0.5.2.2:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/http:=[profile?]
	>=dev-haskell/http-conduit-1.5.0.3:=[profile?]
	>=dev-haskell/http-date-0.0.2:=[profile?]
	>=dev-haskell/http-types-0.7.0:=[profile?]
	>=dev-haskell/network-2.3.0.13:=[profile?]
	>=dev-haskell/old-locale-1.0.0.4:=[profile?]
	>=dev-haskell/sha-1.5.1:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-haskell/transformers-0.3.0.0:=[profile?]
	dev-haskell/unix-compat:=[profile?]
	>=dev-haskell/utf8-string-0.3.7:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	!no-hxt? ( >=dev-haskell/hxt-9.2.2:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag library-only library-only) \
		$(cabal_flag no-hxt no-hxt)
}
