# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Pretty rendering of Ascii diagram into svg or png"
HOMEPAGE="http://hackage.haskell.org/package/asciidiagram"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/fontyfruity-0.5:=[profile?] <dev-haskell/fontyfruity-0.6:=[profile?]
	>=dev-haskell/juicypixels-3.2:=[profile?]
	>=dev-haskell/lens-4.6:=[profile?] <dev-haskell/lens-4.8:=[profile?]
	>=dev-haskell/linear-1.16:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	dev-haskell/optparse-applicative:=[profile?]
	>=dev-haskell/rasterific-svg-0.2:=[profile?] <dev-haskell/rasterific-svg-0.3:=[profile?]
	>=dev-haskell/svg-tree-0.3:=[profile?] <dev-haskell/svg-tree-0.4:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
