# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Paillier"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="a simple Paillier cryptosystem"
HOMEPAGE="http://hackage.haskell.org/package/Paillier"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/crypto-numbers-0.2.2:=[profile?]
	>=dev-haskell/crypto-random-0.0.7:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( dev-haskell/hunit
		>=dev-haskell/quickcheck-2.6
		dev-haskell/test-framework
		dev-haskell/test-framework-quickcheck2
		dev-haskell/test-framework-th )
"

S="${WORKDIR}/${MY_P}"
