# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A wrapper for the Bullet physics engine"
HOMEPAGE="http://www.haskell.org/haskellwiki/Bullet"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/vect-0.4.6:=[profile?] <dev-haskell/vect-1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-pkg-config/bullet
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	>=dev-haskell/cabal-1.2
	virtual/pkgconfig
"
