# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Check whether module and package imports conform to the PVP"
HOMEPAGE="http://www.haskell.org/haskellwiki/Import_modules_properly"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cabal-1.6:= <dev-haskell/cabal-1.19:=
	>=dev-haskell/explicit-exception-0.1.4:= <dev-haskell/explicit-exception-0.2:=
	>=dev-haskell/haskell-src-exts-1.14:= <dev-haskell/haskell-src-exts-1.15:=
	>=dev-haskell/non-empty-0.1.3:= <dev-haskell/non-empty-0.3:=
	>=dev-haskell/transformers-0.2:= <dev-haskell/transformers-0.4:=
	>=dev-haskell/utility-ht-0.0.10:= <dev-haskell/utility-ht-0.1:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
