# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Metering System for OpenStack metrics provided by Vaultaire"
HOMEPAGE="https://github.com/anchor/borel-core"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+network-uri"

RDEPEND=">=dev-haskell/aeson-0.8:=[profile?]
	dev-haskell/async:=[profile?]
	>=dev-haskell/attoparsec-0.12:=[profile?]
	>=dev-haskell/bimap-0.2:=[profile?]
	>=dev-haskell/cassava-0.4:=[profile?]
	>=dev-haskell/ceilometer-common-0.2.2:=[profile?]
	>=dev-haskell/chevalier-common-0.4.0:=[profile?]
	>=dev-haskell/configurator-0.3:=[profile?]
	>=dev-haskell/errors-1.4:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?]
	>=dev-haskell/lens-4.6:=[profile?]
	>=dev-haskell/marquise-4.0.0:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?]
	>=dev-haskell/multiset-0.2:=[profile?]
	>=dev-haskell/pipes-4.1:=[profile?]
	>=dev-haskell/pipes-concurrency-2.0:=[profile?]
	>=dev-haskell/pipes-safe-2.2:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?]
	>=dev-haskell/unordered-containers-0.2.4:=[profile?]
	>=dev-haskell/vaultaire-common-2.8.3:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-haskell/zeromq4-haskell-0.6.3:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	network-uri? ( >=dev-haskell/network-2.6:=[profile?]
			>=dev-haskell/network-uri-2.6:=[profile?] )
	!network-uri? ( <dev-haskell/network-2.6:=[profile?]
			<dev-haskell/network-uri-2.6:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/either-4.3
		>=dev-haskell/hspec-2.1
		>=dev-haskell/lens-properties-4.7
		>=dev-haskell/quickcheck-2.7 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag network-uri network-uri)
}
