# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Validation"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A data-type like Either but with an accumulating Applicative"
HOMEPAGE="http://hackage.haskell.org/package/Validation"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+small_base"

RDEPEND="dev-haskell/category-extras:=[profile?]
	dev-haskell/hunit:=[profile?]
	dev-haskell/quickcheck:2=[profile?]
	dev-haskell/semigroup:=[profile?]
	dev-haskell/test-framework:=[profile?]
	dev-haskell/test-framework-hunit:=[profile?]
	dev-haskell/test-framework-quickcheck2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag small_base small_base)
}
