# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Graphalyze"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Graph-Theoretic Analysis library"
HOMEPAGE="http://hackage.haskell.org/package/Graphalyze"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bktrees-0.2:=[profile?] <dev-haskell/bktrees-0.4:=[profile?]
	>=dev-haskell/fgl-5.4.2.3:=[profile?] <dev-haskell/fgl-5.5:=[profile?]
	>=dev-haskell/graphviz-2999.15:=[profile?] <dev-haskell/graphviz-2999.17:=[profile?]
	dev-haskell/old-locale:=[profile?]
	>=dev-haskell/pandoc-1.12:=[profile?] <dev-haskell/pandoc-1.13:=[profile?]
	dev-haskell/random:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
