# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Atlassian Connect snaplet for the Snap Framework and helper code"
HOMEPAGE="https://bitbucket.org/ajknoll/atlassian-connect-core"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+network-uri"

RDEPEND=">dev-haskell/aeson-0.7.0.3:=[profile?] <dev-haskell/aeson-0.9:=[profile?]
	>=dev-haskell/atlassian-connect-descriptor-0.2:=[profile?]
	>=dev-haskell/base64-bytestring-1.0:=[profile?] <dev-haskell/base64-bytestring-1.1:=[profile?]
	>=dev-haskell/case-insensitive-1:=[profile?] <dev-haskell/case-insensitive-2:=[profile?]
	>=dev-haskell/cipher-aes-0.2:=[profile?] <dev-haskell/cipher-aes-0.3:=[profile?]
	>=dev-haskell/configurator-0.3:=[profile?] <dev-haskell/configurator-0.4:=[profile?]
	>=dev-haskell/cryptohash-0.11:=[profile?] <dev-haskell/cryptohash-0.12:=[profile?]
	>=dev-haskell/hostname-1:=[profile?] <dev-haskell/hostname-2:=[profile?]
	>=dev-haskell/http-client-0.3:=[profile?] <dev-haskell/http-client-0.4:=[profile?]
	>=dev-haskell/http-media-0.4:=[profile?] <dev-haskell/http-media-0.5:=[profile?]
	>=dev-haskell/http-types-0.8:=[profile?] <dev-haskell/http-types-0.9:=[profile?]
	>=dev-haskell/jwt-0.3:=[profile?] <dev-haskell/jwt-0.5:=[profile?]
	>=dev-haskell/mtl-2:=[profile?] <dev-haskell/mtl-3:=[profile?]
	>=dev-haskell/network-api-support-0.1:=[profile?] <dev-haskell/network-api-support-0.2:=[profile?]
	>=dev-haskell/snap-0.13.3:=[profile?] <dev-haskell/snap-0.14:=[profile?]
	>=dev-haskell/snap-core-0.9:=[profile?] <dev-haskell/snap-core-0.10:=[profile?]
	>=dev-haskell/split-0.2:=[profile?] <dev-haskell/split-0.3:=[profile?]
	>=dev-haskell/text-0.11:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/time-units-1:=[profile?] <dev-haskell/time-units-2:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-0.5:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	network-uri? ( >=dev-haskell/network-2.6:=[profile?]
			>=dev-haskell/network-uri-2.6:=[profile?] )
	!network-uri? ( <dev-haskell/network-2.6:=[profile?]
			<dev-haskell/network-uri-2.6:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag network-uri network-uri)
}
