# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin test-suite"
inherit haskell-cabal

MY_PN="Buster"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Hits a set of urls periodically to bust caches"
HOMEPAGE="http://github.com/michaelxavier/Buster"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/conduit-0.5:= <dev-haskell/conduit-0.6:=
	>=dev-haskell/data-default-0.5:= <dev-haskell/data-default-0.6:=
	>=dev-haskell/errors-1.4:= <dev-haskell/errors-1.5:=
	>=dev-haskell/hinotify-0.3:= <dev-haskell/hinotify-0.4:=
	>=dev-haskell/hslogger-1.2:= <dev-haskell/hslogger-1.3:=
	>=dev-haskell/http-conduit-1.8:= <dev-haskell/http-conduit-1.9:=
	>=dev-haskell/http-types-0.7:= <dev-haskell/http-types-0.8:=
	dev-haskell/transformers:=
	>=dev-haskell/unbounded-delays-0.1:= <dev-haskell/unbounded-delays-0.2:=
	>=dev-haskell/yaml-0.8:= <dev-haskell/yaml-0.9:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/hspec-1.4 <dev-haskell/hspec-1.5
		>=dev-haskell/hspec-expectations-0.3 <dev-haskell/hspec-expectations-0.4
		dev-haskell/string-qq
		>=dev-haskell/temporary-1.1 <dev-haskell/temporary-1.2 )
"

S="${WORKDIR}/${MY_P}"
