# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Xec"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Gtk command launcher with identicon"
HOMEPAGE="http://hackage.haskell.org/package/Xec"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.4:=
	dev-haskell/cairo:=
	dev-haskell/gtk:=
	dev-haskell/mtl:=
	dev-haskell/old-time:=
	dev-haskell/sha:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
