# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="DSL for generating API boilerplate and docs"
HOMEPAGE="http://github.com/iconnect/api-tools"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.6.2:=[profile?] <dev-haskell/aeson-0.7:=[profile?]
	<=dev-haskell/aeson-pretty-0.7:=[profile?]
	>=dev-haskell/attoparsec-0.10.4:=[profile?]
	>=dev-haskell/base64-bytestring-1.0:=[profile?] <dev-haskell/base64-bytestring-1.1:=[profile?]
	>=dev-haskell/cabal-1.9.2:=[profile?]
	>=dev-haskell/case-insensitive-1.0:=[profile?]
	>=dev-haskell/lens-3.8.7:=[profile?]
	>=dev-haskell/old-locale-1.0.0.4:=[profile?]
	>=dev-haskell/quickcheck-2.5.1:2=[profile?]
	>=dev-haskell/regex-compat-tdfa-0.95.1:=[profile?]
	>=dev-haskell/safe-0.3.3:=[profile?]
	>=dev-haskell/safecopy-0.8.1:=[profile?]
	>=dev-haskell/text-0.11:=[profile?]
	>=dev-haskell/unordered-containers-0.2.3.0:=[profile?]
	>=dev-haskell/vector-0.10.0.1:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/alex
	>=dev-haskell/cabal-1.16.0
	dev-haskell/happy
	test? ( >=dev-haskell/tasty-0.3
		>=dev-haskell/tasty-hunit-0.2
		>=dev-haskell/tasty-quickcheck-0.3 )
"
