# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Condor"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Information retrieval library"
HOMEPAGE="https://github.com/klangner/Condor"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.5.1:=[profile?] <dev-haskell/binary-0.6:=[profile?]
	>=dev-haskell/glider-nlp-0.1:=[profile?] <dev-haskell/glider-nlp-1:=[profile?]
	>=dev-haskell/text-1:=[profile?] <dev-haskell/text-1.1:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/cabal-1.16.0 <dev-haskell/cabal-1.17
		>=dev-haskell/hunit-1.2.5 <dev-haskell/hunit-1.3 )
"

S="${WORKDIR}/${MY_P}"
