# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Add TLS support for Data.Acid.Remote"
HOMEPAGE="http://acid-state.seize.it/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/acid-state-0.9:=[profile?] <dev-haskell/acid-state-0.13:=[profile?]
	<dev-haskell/hsopenssl-0.11:=[profile?]
	<dev-haskell/network-2.6:=[profile?]
	>=dev-haskell/safecopy-0.6:=[profile?] <dev-haskell/safecopy-0.9:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
