# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="MuCheck-QuickCheck"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Automated Mutation Testing for QuickCheck tests"
HOMEPAGE="https://bitbucket.com/osu-testing/mucheck-quickcheck"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/missingh-1.3:=[profile?]
	>=dev-haskell/mucheck-0.2.1:=[profile?] <dev-haskell/mucheck-0.2.2:=[profile?]
	>=dev-haskell/quickcheck-2.6:2=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"

S="${WORKDIR}/${MY_P}"
