# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="CPL"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An interpreter of Hagino's Categorical Programming Language (CPL)"
HOMEPAGE="http://hackage.haskell.org/package/CPL"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="haskeline readline"

RDEPEND="dev-haskell/mtl:=
	dev-haskell/parsec:=
	>=dev-lang/ghc-7.4.1:=
	readline? ( dev-haskell/readline:= )
	!readline? ( haskeline? ( dev-haskell/haskeline:= ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag haskeline haskeline) \
		$(cabal_flag readline readline)
}
