# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="XSaiga"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An implementation of a polynomial-time top-down parser suitable for NLP"
HOMEPAGE="http://hafiz.myweb.cs.uwindsor.ca/proHome.html"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cgi-3001.1:=[profile?] <dev-haskell/cgi-3001.2:=[profile?]
	>=dev-haskell/hsparql-0.2:=[profile?] <dev-haskell/hsparql-0.3:=[profile?]
	>=dev-haskell/rdf4h-1.2:=[profile?] <dev-haskell/rdf4h-1.3:=[profile?]
	>=dev-haskell/text-0.11:=[profile?] <dev-haskell/text-0.12:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
