# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="LambdaShell"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Simple shell for evaluating lambda expressions"
HOMEPAGE="http://hackage.haskell.org/package/LambdaShell"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-1.0:=
	>=dev-haskell/parsec-1.0:=
	>=dev-haskell/readline-1.0:=
	>=dev-haskell/shellac-0.9:=
	>=dev-haskell/shellac-readline-0.9:=
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/readline
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"
