# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HAppS-IxSet"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Web framework"
HOMEPAGE="http://hackage.haskell.org/package/HAppS-IxSet"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/happs-data-0.9.3:=[profile?]
	>=dev-haskell/happs-state-0.9.3:=[profile?]
	>=dev-haskell/happs-util-0.9.3:=[profile?]
	>=dev-haskell/hslogger-1.0.2:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/syb-with-class:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
