# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HPlot"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A minimal monadic PLplot interface for Haskell"
HOMEPAGE="http://hackage.haskell.org/package/HPlot"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/glade:=[profile?]
	dev-haskell/glib:=[profile?]
	dev-haskell/gtk:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-pkg-config/plplotd-gnome2
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	>=dev-haskell/cabal-1.2
	virtual/pkgconfig
"

S="${WORKDIR}/${MY_P}"
