# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A build-system library and driver"
HOMEPAGE="http://hackage.haskell.org/package/cake"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.5:=[profile?] <dev-haskell/binary-0.6:=[profile?]
	>=dev-haskell/cmdargs-0.9:=[profile?] <dev-haskell/cmdargs-0.10:=[profile?]
	>=dev-haskell/derive-2.5:=[profile?] <dev-haskell/derive-2.6:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/puremd5-2.1:=[profile?] <dev-haskell/puremd5-2.2:=[profile?]
	>=dev-haskell/regex-tdfa-1.1:=[profile?] <dev-haskell/regex-tdfa-1.2:=[profile?]
	>=dev-haskell/split-0.1:=[profile?] <dev-haskell/split-0.2:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
