# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="RNAFold"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="RNA secondary structure prediction"
HOMEPAGE="http://www.tbi.univie.ac.at/~choener/adpfusion"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+llvm"

RDEPEND="~dev-haskell/adpfusion-0.0.1.2:=[profile?]
	~dev-haskell/biobasevienna-0.2.2.5:=[profile?]
	~dev-haskell/biobasexna-0.6.2.5:=[profile?]
	>=dev-haskell/mtl-2:=[profile?]
	>=dev-haskell/primitive-0.4:=[profile?] <dev-haskell/primitive-0.5:=[profile?]
	~dev-haskell/primitivearray-0.2.2.0:=[profile?]
	>=dev-haskell/strict-0.3.2:=[profile?]
	>=dev-haskell/vector-0.9:=[profile?] <dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6.0
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag llvm llvm)
}
