# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Hermes"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Message-based middleware layer"
HOMEPAGE="http://hackage.haskell.org/package/Hermes"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aes-0.2.4:=[profile?]
	>=dev-haskell/cereal-0.2:=[profile?]
	>=dev-haskell/hslogger-1.0.7:=[profile?]
	>=dev-haskell/monads-tf-0.1:=[profile?] <dev-haskell/monads-tf-0.2:=[profile?]
	dev-haskell/network:=[profile?]
	dev-haskell/old-time:=[profile?]
	dev-haskell/random:=[profile?]
	>=dev-haskell/rsa-1.0.2:=[profile?]
	>=dev-haskell/sha2-0.1.1:=[profile?]
	dev-haskell/stm:=[profile?]
	>=dev-haskell/syb-0.1:=[profile?] <dev-haskell/syb-0.2:=[profile?]
	>=dev-haskell/transformers-0.1.4.0:=[profile?]
	>=dev-haskell/unamb-0.2.2:=[profile?]
	>=dev-haskell/yjtools-0.9.7:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
