# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="abcBridge"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Bindings for ABC, A System for Sequential Synthesis and Verification"
HOMEPAGE="http://hackage.haskell.org/package/abcBridge"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+enable-pthreads"

RDEPEND="dev-haskell/aig:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/abc
	enable-pthreads? ( virtual/libc )
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	>=dev-haskell/cabal-1.10
	test? ( >=dev-haskell/quickcheck-2.7
		dev-haskell/tasty
		dev-haskell/tasty-ant-xml
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck )
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag enable-pthreads enable-pthreads)
}
