# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="BSON documents are JSON-like objects with a standard binary encoding"
HOMEPAGE="http://github.com/TonyGen/bson-haskell"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=[profile?]
	dev-haskell/compact-string-fix:=[profile?]
	dev-haskell/cryptohash:=[profile?]
	dev-haskell/data-binary-ieee754:=[profile?]
	>=dev-haskell/mtl-2:=[profile?]
	dev-haskell/network:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/file-location-0.4 <dev-haskell/file-location-0.5
		>=dev-haskell/hspec-0.6.1 <dev-haskell/hspec-0.7
		dev-haskell/hunit
		>=dev-haskell/quickcheck-2.4 <dev-haskell/quickcheck-2.5 )
"
