# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Examples using the Accelerate library"
HOMEPAGE="https://github.com/AccelerateHS/accelerate-examples"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+cuda +ekg +gui opencl"

RDEPEND=">=dev-lang/ghc-7.4.1:=
	cuda? ( >=dev-haskell/accelerate-cuda-0.14:= <dev-haskell/accelerate-cuda-0.15:= )
	ekg? ( >=dev-haskell/ekg-0.3:= <dev-haskell/ekg-0.4:= )
	opencl? ( >=dev-haskell/accelerate-opencl-0.1:= <dev-haskell/accelerate-opencl-0.2:= )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag cuda cuda) \
		$(cabal_flag ekg ekg) \
		$(cabal_flag gui gui) \
		$(cabal_flag opencl opencl)
}
