# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Examples using the Accelerate library"
HOMEPAGE="http://www.cse.unsw.edu.au/~chak/project/accelerate/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+cuda +io +opencl"

RDEPEND=">=dev-haskell/accelerate-0.12:=
	>=dev-haskell/accelerate-io-0.12:=
	>=dev-haskell/attoparsec-0.10:=
	>=dev-haskell/bmp-1.2:=
	>=dev-haskell/bytestring-lexing-0.2:=
	>=dev-haskell/cmdargs-0.6:=
	>=dev-haskell/criterion-0.5:=
	>=dev-haskell/fclabels-1.0:=
	>=dev-haskell/gloss-1.7:=
	>=dev-haskell/hashtables-1.0.1:=
	>=dev-haskell/mtl-1.1:=
	>=dev-haskell/mwc-random-0.8:=
	>=dev-haskell/pgm-0.1:=
	>=dev-haskell/quickcheck-2.0:2=
	dev-haskell/random:=
	>=dev-haskell/test-framework-0.5:=
	>=dev-haskell/test-framework-quickcheck2-0.2:=
	>=dev-haskell/vector-0.7:=
	>=dev-haskell/vector-algorithms-0.4:=
	>=dev-lang/ghc-7.4.1:=
	sys-devel/gcc[cxx]
	cuda? ( >=dev-haskell/accelerate-cuda-0.12:=
		>=dev-haskell/cuda-0.4:= )
	opencl? ( >=dev-haskell/accelerate-opencl-0.1:= <dev-haskell/accelerate-opencl-0.2:= )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag cuda cuda) \
		$(cabal_flag io io) \
		$(cabal_flag opencl opencl)
}
