# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Examples using the Accelerate library"
HOMEPAGE="http://hackage.haskell.org/package/accelerate-examples"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+cuda io"

RDEPEND=">=dev-haskell/accelerate-0.10:= <dev-haskell/accelerate-0.11:=
	>=dev-haskell/attoparsec-0.8:= <dev-haskell/attoparsec-0.9:=
	>=dev-haskell/bytestring-lexing-0.2:= <dev-haskell/bytestring-lexing-0.3:=
	>=dev-haskell/cmdargs-0.6:= <dev-haskell/cmdargs-0.7:=
	>=dev-haskell/criterion-0.5:= <dev-haskell/criterion-0.6:=
	>=dev-haskell/mtl-1.1:= <dev-haskell/mtl-3.0:=
	>=dev-haskell/mwc-random-0.8:= <dev-haskell/mwc-random-0.9:=
	>=dev-haskell/pgm-0.1:= <dev-haskell/pgm-0.2:=
	>=dev-haskell/vector-0.7:= <dev-haskell/vector-0.8:=
	>=dev-haskell/vector-algorithms-0.4:= <dev-haskell/vector-algorithms-0.5:=
	>=dev-lang/ghc-7.4.1:=
	sys-devel/gcc[cxx]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag cuda cuda) \
		$(cabal_flag io io)
}
