# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="CSPM-Frontend"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A CSP-M parser compatible with FDR-2.83"
HOMEPAGE="http://hackage.haskell.org/package/CSPM-Frontend"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="testing"

RDEPEND="dev-haskell/mtl:=[profile?]
	dev-haskell/old-time:=[profile?]
	>=dev-haskell/parsec-2.1.0.0:=[profile?] <dev-haskell/parsec-3.0:=[profile?]
	dev-haskell/syb:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag testing testing)
}
