# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="GtkGLTV"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="OpenGL support for Gtk-based GUIs for Tangible Values"
HOMEPAGE="http://hackage.haskell.org/package/GtkGLTV"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/bitmap:=[profile?]
	dev-haskell/bitmap-opengl:=[profile?]
	dev-haskell/gtk:=[profile?]
	dev-haskell/gtkglext:=[profile?]
	dev-haskell/gtktv:=[profile?]
	dev-haskell/opengl:=[profile?]
	dev-haskell/stb-image:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
