# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="YACPong"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Yet Another Pong Clone using SDL"
HOMEPAGE="http://github.com/snkkid/YACPong"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/data-accessor-transformers:=
	dev-haskell/fclabels:=
	dev-haskell/monads-fd:=
	dev-haskell/random:=
	dev-haskell/sdl:=
	dev-haskell/sdl-image:=
	dev-haskell/sdl-mixer:=
	dev-haskell/sdl-ttf:=
	dev-haskell/transformers:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4
"

S="${WORKDIR}/${MY_P}"
