# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="LogicGrowsOnTrees-MPI"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="an adapter for LogicGrowsOnTrees that uses MPI"
HOMEPAGE="http://hackage.haskell.org/package/LogicGrowsOnTrees-MPI"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="tests warnings"

RDEPEND=">=dev-haskell/cereal-0.3:=[profile?] <dev-haskell/cereal-0.4:=[profile?]
	>=dev-haskell/cmdtheline-0.2:=[profile?] <dev-haskell/cmdtheline-0.3:=[profile?]
	>=dev-haskell/data-ivar-0.30:=[profile?] <dev-haskell/data-ivar-1.0:=[profile?]
	>=dev-haskell/derive-2.5.9:=[profile?] <dev-haskell/derive-2.6:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-1.3:=[profile?]
	>=dev-haskell/hslogger-template-2.0:=[profile?] <dev-haskell/hslogger-template-2.1:=[profile?]
	>=dev-haskell/logicgrowsontrees-1.0:=[profile?] <dev-haskell/logicgrowsontrees-1.1:=[profile?]
	>=dev-haskell/monadcatchio-transformers-0.3:=[profile?] <dev-haskell/monadcatchio-transformers-0.4:=[profile?]
	>=dev-haskell/stm-2.4:=[profile?] <dev-haskell/stm-2.5:=[profile?]
	>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/mpi
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag tests tests) \
		$(cabal_flag warnings warnings)
}
