# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="A queue daemon for Amazon's SES with a PostgreSQL table as a queue"
HOMEPAGE="https://github.com/dbp/amazon-emailer"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/http-conduit-2:= <dev-haskell/http-conduit-3:=
	>=dev-haskell/lifted-base-0.2:= <dev-haskell/lifted-base-0.3:=
	>=dev-haskell/mime-mail-0.4:= <dev-haskell/mime-mail-0.5:=
	>=dev-haskell/mime-mail-ses-0.2:= <dev-haskell/mime-mail-ses-0.3:=
	>=dev-haskell/postgresql-simple-0.3:= <dev-haskell/postgresql-simple-0.4:=
	>=dev-haskell/resourcet-0.4:= <dev-haskell/resourcet-0.5:=
	>=dev-haskell/text-0.11:= <dev-haskell/text-0.12:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
