# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="a faster debian repository"
HOMEPAGE="https://github.com/pyr/apotiki"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.6.2.1:=[profile?]
	>=dev-haskell/attoparsec-0.10.4.0:=[profile?]
	>=dev-haskell/binary-0.7.1.0:=[profile?]
	~dev-haskell/crypto-api-0.12.2.2:=[profile?]
	>=dev-haskell/cryptohash-0.9.1:=[profile?]
	>=dev-haskell/http-types-0.8.3:=[profile?]
	>=dev-haskell/old-time-1.1.0.1:=[profile?]
	>=dev-haskell/openpgp-0.6.1:=[profile?]
	>=dev-haskell/openpgp-asciiarmor-0.1:=[profile?]
	>=dev-haskell/openpgp-crypto-api-0.6.3:=[profile?]
	>=dev-haskell/scotty-0.6.2:=[profile?]
	>=dev-haskell/strict-0.3.2:=[profile?]
	>=dev-haskell/tar-0.4.0.1:=[profile?]
	>=dev-haskell/text-1.0.0.1:=[profile?]
	>=dev-haskell/transformers-0.3.0.0:=[profile?]
	>=dev-haskell/wai-extra-2.0.3.1:=[profile?]
	>=dev-haskell/wai-middleware-static-0.4.0.2:=[profile?]
	>=dev-haskell/zlib-0.5.4.1:=[profile?]
	>=dev-lang/ghc-7.6.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
