# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Examples of 3D graphics programming with OpenGL"
HOMEPAGE="http://darcs.wolfgang.jeltsch.info/haskell/3d-graphics-examples"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/glut-2.4:= <dev-haskell/glut-2.6:=
	>=dev-haskell/opengl-2.8:= <dev-haskell/opengl-2.10:=
	>=dev-haskell/random-1.0:= <dev-haskell/random-1.1:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
