# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="LambdaINet"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Graphical Interaction Net Evaluator for Optimal Evaluation"
HOMEPAGE="not available"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/glfw-0.5.0.0:=
	dev-haskell/glfw-task:=
	dev-haskell/monad-task:=
	dev-haskell/mtl:=
	dev-haskell/opengl:=
	dev-haskell/transformers:=
	dev-haskell/vector:=
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
