# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="JSONb"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="JSON parser that uses byte strings"
HOMEPAGE="http://github.com/solidsnack/JSONb/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="cli"

RDEPEND=">=dev-haskell/attoparsec-0.10:=[profile?]
	>=dev-haskell/bytestring-nums-0.3.1:=[profile?]
	>=dev-haskell/bytestring-trie-0.1.4:=[profile?]
	>=dev-haskell/utf8-string-0.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag cli cli)
}
