# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="HPong"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A simple OpenGL Pong game based on GLFW"
HOMEPAGE="http://bonsaicode.wordpress.com/2009/04/23/hpong-012/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/data-accessor:=
	dev-haskell/data-accessor-template:=
	dev-haskell/glfw:=
	dev-haskell/opengl:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	dev-haskell/cabal
"

S="${WORKDIR}/${MY_P}"
