# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="VKHS"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Provides access to Vkontakte social network, popular in Russia"
HOMEPAGE="http://github.com/ierton/vkhs"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bimap-0.2:=[profile?] <dev-haskell/bimap-0.3:=[profile?]
	>=dev-haskell/curlhs-0.0:=[profile?] <dev-haskell/curlhs-0.1:=[profile?]
	>=dev-haskell/failure-0.2:=[profile?] <dev-haskell/failure-0.3:=[profile?]
	>=dev-haskell/json-0.5:=[profile?] <dev-haskell/json-0.6:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?] <dev-haskell/safe-0.4:=[profile?]
	>=dev-haskell/split-0.2:=[profile?] <dev-haskell/split-0.3:=[profile?]
	>=dev-haskell/tagsoup-0.12:=[profile?] <dev-haskell/tagsoup-0.13:=[profile?]
	>=dev-haskell/tagsoup-parsec-0.0:=[profile?] <dev-haskell/tagsoup-parsec-0.1:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-haskell/utf8-string-0.3:=[profile?] <dev-haskell/utf8-string-0.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
