# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="VKHS"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Provides access to Vkontakte social network via public API"
HOMEPAGE="http://github.com/grwlf/vkhs"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/bimap:=[profile?]
	dev-haskell/curlhs:=[profile?]
	dev-haskell/failure:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/optparse-applicative-0.11:=[profile?] <dev-haskell/optparse-applicative-0.12:=[profile?]
	dev-haskell/parsec:=[profile?]
	dev-haskell/pretty-show:=[profile?]
	dev-haskell/regexpr:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/split:=[profile?]
	dev-haskell/tagsoup:=[profile?]
	dev-haskell/tagsoup-parsec:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/transformers:=[profile?]
	dev-haskell/utf8-string:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	net-misc/curl
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
