# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="ActionKid"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An easy-to-use video game framework for Haskell"
HOMEPAGE="http://adit.io"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/gloss:=[profile?]
	dev-haskell/gloss-juicy:=[profile?]
	>=dev-haskell/juicypixels-3.1:=[profile?] <dev-haskell/juicypixels-3.2:=[profile?]
	~dev-haskell/juicypixels-repa-0.7:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/opengl-2.8.0:=[profile?] <dev-haskell/opengl-2.8.1:=[profile?]
	dev-haskell/statevar:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( dev-haskell/hspec )
"

S="${WORKDIR}/${MY_P}"
