# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="AgentX protocol for write SNMP subagents"
HOMEPAGE="http://hackage.haskell.org/package/agentx"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="example"

RDEPEND="dev-haskell/binary:=[profile?]
	dev-haskell/bitwise:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/diff:=[profile?]
	dev-haskell/fclabels:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/network:=[profile?]
	dev-haskell/pipes:=[profile?]
	dev-haskell/pipes-concurrency:=[profile?]
	dev-haskell/pipes-network:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/snmp:=[profile?]
	dev-haskell/transformers:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag example example)
}
