# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Bindings to libaosd, a library for Cairo-based on-screen displays"
HOMEPAGE="http://hackage.haskell.org/package/aosd"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="debugmemory"

RDEPEND=">=dev-haskell/bindings-dsl-1.0.11:=[profile?]
	>=dev-haskell/cairo-0.12:=[profile?]
	dev-haskell/colour:=[profile?]
	dev-haskell/monad-control:=[profile?]
	>=dev-haskell/pango-0.12:=[profile?]
	dev-haskell/transformers:=[profile?]
	dev-haskell/x11:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-pkg-config/libaosd
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	virtual/pkgconfig
	test? ( dev-haskell/language-haskell-extract )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag debugmemory debugmemory)
}
