# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Various modules and constructs inspired by category theory"
HOMEPAGE="http://comonad.com/reader/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+arrowsubclassescategory optimize +typefamilies"

RDEPEND=">=dev-haskell/mtl-1.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	arrowsubclassescategory? ( >=dev-haskell/ghc-6.9:=[profile?] )
	!arrowsubclassescategory? ( <dev-haskell/ghc-6.9:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag arrowsubclassescategory arrowsubclassescategory) \
		$(cabal_flag optimize optimize) \
		$(cabal_flag typefamilies typefamilies)
}
