# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Redmine"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Library to access Redmine's REST services"
HOMEPAGE="https://github.com/lookunder/RedmineHs"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/connection:=[profile?]
	dev-haskell/http:=[profile?]
	dev-haskell/http-client-tls:=[profile?]
	>=dev-haskell/http-conduit-2.1.0:=[profile?]
	dev-haskell/http-types:=[profile?]
	dev-haskell/missingh:=[profile?]
	dev-haskell/network:=[profile?]
	dev-haskell/old-locale:=[profile?]
	dev-haskell/old-time:=[profile?]
	dev-haskell/resourcet:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/transformers:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	test? ( dev-haskell/hunit )
"

S="${WORKDIR}/${MY_P}"
