# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin test-suite"
inherit haskell-cabal

DESCRIPTION="Go-to-definition for Haskell"
HOMEPAGE="https://github.com/feuerbach/ariadne"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/async:=
	>=dev-haskell/bert-1.2:=
	>=dev-haskell/cabal-1.16:=
	dev-haskell/data-lens:=
	dev-haskell/data-lens-fd:=
	dev-haskell/data-lens-template:=
	>=dev-haskell/haskell-names-0.4.1:=
	>=dev-haskell/haskell-packages-0.2:=
	>=dev-haskell/haskell-src-exts-1.16:=
	>=dev-haskell/hse-cpp-0.1:=
	>=dev-haskell/hslogger-1.2:=
	>=dev-haskell/mtl-2.1:=
	dev-haskell/stm:=
	dev-haskell/tagged:=
	dev-haskell/transformers:=
	>=dev-haskell/utf8-string-0.3:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	test? ( >=dev-haskell/tasty-0.7
		>=dev-haskell/tasty-hunit-0.4 )
"
