# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HGamer3D-SFML-Binding"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="SFML Binding for HGamer3D"
HOMEPAGE="http://www.hgamer3d.org"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/hgamer3d-data-0.3.0:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/:libsfml-audio.so.2
	unknown-c-lib/:libsfml-system.so.2
	unknown-c-lib/:libsfml-window.so.2
	unknown-c-lib/hg3dsfml030
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4
"

S="${WORKDIR}/${MY_P}"
