# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HLearn-datastructures"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="This package contains commonly used data structures"
HOMEPAGE="http://hackage.haskell.org/package/HLearn-datastructures"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/constraintkinds-0.1.0:=[profile?]
	>=dev-haskell/hlearn-algebra-1.1.0:=[profile?]
	>=dev-haskell/list-extras-0.4.1:=[profile?]
	>=dev-haskell/monadrandom-0.1.9:=[profile?]
	>=dev-haskell/quickcheck-2.3.1:2=[profile?]
	>=dev-haskell/vector-0.10.0:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
