# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="low level bindings to casadi-snopt_interface"
HOMEPAGE="http://hackage.haskell.org/package/casadi-bindings-snopt-interface"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="LGPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/casadi-bindings-core:=[profile?]
	dev-haskell/casadi-bindings-internal:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	sys-devel/gcc[cxx]
	unknown-pkg-config/casadi_snopt_interface
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	virtual/pkgconfig
"
