# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="BlogLiterately"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A tool for posting Haskelly articles to blogs"
HOMEPAGE="http://byorgey.wordpress.com/blogliterately/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/blaze-html-0.5:= <dev-haskell/blaze-html-0.6:=
	>=dev-haskell/cmdargs-0.9.5:= <dev-haskell/cmdargs-0.10:=
	>=dev-haskell/haxml-1.22:= <dev-haskell/haxml-1.23:=
	>=dev-haskell/haxr-3000.8:= <dev-haskell/haxr-3000.9:=
	>=dev-haskell/hscolour-1.20:= <dev-haskell/hscolour-1.21:=
	>=dev-haskell/pandoc-1.9:= <dev-haskell/pandoc-1.10:=
	>=dev-haskell/parsec-3:= <dev-haskell/parsec-3.2:=
	>=dev-haskell/transformers-0.3:= <dev-haskell/transformers-0.4:=
	>=dev-haskell/utf8-string-0.3:= <dev-haskell/utf8-string-0.4:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
