# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Spock"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Another Haskell web framework for rapid development"
HOMEPAGE="https://github.com/agrafix/Spock"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.6.2.1:=[profile?] <dev-haskell/aeson-0.8:=[profile?]
	>=dev-haskell/base64-bytestring-1:=[profile?] <dev-haskell/base64-bytestring-2:=[profile?]
	>=dev-haskell/blaze-html-0.7:=[profile?] <dev-haskell/blaze-html-0.8:=[profile?]
	>=dev-haskell/case-insensitive-1.1:=[profile?] <dev-haskell/case-insensitive-1.2:=[profile?]
	>=dev-haskell/conduit-1.0:=[profile?] <dev-haskell/conduit-1.2:=[profile?]
	>=dev-haskell/digestive-functors-0.7:=[profile?] <dev-haskell/digestive-functors-0.8:=[profile?]
	>=dev-haskell/hashable-1.2:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/http-types-0.8:=[profile?] <dev-haskell/http-types-0.9:=[profile?]
	>=dev-haskell/monad-control-0.3:=[profile?] <dev-haskell/monad-control-0.4:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/old-locale-1:=[profile?] <dev-haskell/old-locale-2:=[profile?]
	>=dev-haskell/path-pieces-0.1:=[profile?] <dev-haskell/path-pieces-0.2:=[profile?]
	>=dev-haskell/pool-conduit-0.1:=[profile?] <dev-haskell/pool-conduit-0.2:=[profile?]
	>=dev-haskell/random-1:=[profile?] <dev-haskell/random-2:=[profile?]
	>=dev-haskell/regex-compat-0.95:=[profile?] <dev-haskell/regex-compat-0.96:=[profile?]
	>=dev-haskell/resource-pool-0.2:=[profile?] <dev-haskell/resource-pool-0.3:=[profile?]
	>=dev-haskell/resourcet-0.4:=[profile?] <dev-haskell/resourcet-0.5:=[profile?]
	>=dev-haskell/stm-2.4:=[profile?] <dev-haskell/stm-2.5:=[profile?]
	>=dev-haskell/text-0.11.3.1:=[profile?] <dev-haskell/text-1.2:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-haskell/transformers-base-0.4:=[profile?] <dev-haskell/transformers-base-0.5:=[profile?]
	>=dev-haskell/unordered-containers-0.2:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-haskell/vault-0.3:=[profile?] <dev-haskell/vault-0.4:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?] <dev-haskell/vector-0.11:=[profile?]
	>=dev-haskell/wai-2.0:=[profile?]
	>=dev-haskell/wai-extra-2.0.0.1:=[profile?]
	~dev-haskell/wai-util-0.7:=[profile?]
	>=dev-haskell/warp-2.0.0.1:=[profile?] <dev-haskell/warp-2.1:=[profile?]
	>=dev-haskell/xsd-0.4:=[profile?] <dev-haskell/xsd-0.5:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/htf-0.11 <dev-haskell/htf-0.12 )
"

S="${WORKDIR}/${MY_P}"
