# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="MetaHDBC"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Statically checked database access"
HOMEPAGE="http://hackage.haskell.org/package/MetaHDBC"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/convertible-1.0.10.0:=[profile?]
	>=dev-haskell/hashtables-1.2.0.0:=[profile?]
	>=dev-haskell/hdbc-2.2.7.0:2=[profile?]
	>=dev-haskell/hdbc-odbc-2.2.3.0:=[profile?] <dev-haskell/hdbc-odbc-2.4.0.0:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

S="${WORKDIR}/${MY_P}"
