# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Monad to ease implementing a binary network protocol over ZeroMQ"
HOMEPAGE="http://github.com/NicolasT/binary-protocol-zmq"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+optimize tests"

RDEPEND="dev-haskell/binary:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/zeromq-haskell:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	tests? ( dev-haskell/hunit:=[profile?]
			dev-haskell/test-framework:=[profile?]
			dev-haskell/test-framework-hunit:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag optimize optimize) \
		$(cabal_flag tests tests)
}
