# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="ChristmasTree"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Alternative approach of 'read' that composes grammars instead of parsers"
HOMEPAGE="http://www.cs.uu.nl/wiki/bin/view/Center/TTTAS"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="LGPL-2.1"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/fgl-5.4.2:=[profile?] <dev-haskell/fgl-5.4.3:=[profile?]
	>=dev-haskell/tttas-0.4:=[profile?]
	>=dev-haskell/uulib-0.9.11:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2.3.1
"

S="${WORKDIR}/${MY_P}"
