# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="WMSigner"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="WebMoney authentication module"
HOMEPAGE="http://hackage.haskell.org/package/WMSigner"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/base64-bytestring-1:=[profile?]
	>=dev-haskell/binary-0.5:=[profile?]
	dev-haskell/cryptohash:=[profile?]
	>=dev-haskell/lens-4.4:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?]
	>=dev-haskell/random-1.0.1:=[profile?]
	>=dev-haskell/split-0.2:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( dev-haskell/hspec )
"

S="${WORKDIR}/${MY_P}"
