# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="JsContracts"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Design-by-contract for JavaScript"
HOMEPAGE="http://www.cs.brown.edu/research/plt/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-1.1.0.1:=[profile?]
	<dev-haskell/parsec-3.0.0:=[profile?]
	>=dev-haskell/syb-0.1:=[profile?]
	~dev-haskell/webbits-1.0:=[profile?]
	~dev-haskell/webbits-html-1.0.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2.3
"

S="${WORKDIR}/${MY_P}"
