# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Automatically bump package versions, also transitively"
HOMEPAGE="http://github.com/silkapp/bumper"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cabal-1.6:= <dev-haskell/cabal-1.23:=
	>=dev-haskell/fclabels-1.0:= <dev-haskell/fclabels-2.1:=
	>=dev-haskell/regex-compat-0.93:= <dev-haskell/regex-compat-0.96:=
	>=dev-haskell/split-0.1:= <dev-haskell/split-0.3:=
	~dev-haskell/strict-0.3.2:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
