# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Scurry"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A cross platform P2P VPN application built using Haskell"
HOMEPAGE="http://code.google.com/p/scurry/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.4.3.1:=
	>=dev-haskell/network-2.1.0.0:=
	>=dev-haskell/network-bytestring-0.1.1.2:=
	>=dev-haskell/parsec-3.0.0:=
	>=dev-haskell/random-1.0.0.0:=
	>=dev-haskell/stm-2.1.1.0:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2.0
"

S="${WORKDIR}/${MY_P}"
