# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Framework for inferring generative probabilistic models with Gibbs sampling"
HOMEPAGE="https://github.com/bgamari/bayes-stack"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/cereal:=[profile?]
	dev-haskell/digamma:=[profile?]
	dev-haskell/enummapset:=[profile?]
	dev-haskell/gamma:=[profile?]
	dev-haskell/logfloat:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/mwc-random:=[profile?]
	dev-haskell/random-fu:=[profile?]
	dev-haskell/random-source:=[profile?]
	dev-haskell/rvar:=[profile?]
	dev-haskell/statistics:=[profile?]
	dev-haskell/stm:=[profile?]
	dev-haskell/transformers:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
