# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Rasenschach"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Soccer simulation"
HOMEPAGE="http://patch-tag.com/r/martingw/Rasenschach/wiki/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/convertible:=
	dev-haskell/ghc:=
	dev-haskell/monad-loops:=
	dev-haskell/sdl:=
	dev-haskell/sdl-gfx:=
	dev-haskell/sdl-image:=
	dev-haskell/sdl-mixer:=
	dev-haskell/sdl-ttf:=
	dev-haskell/yampa:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
