# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="SourceGraph"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Use graph-theory to analyse your code"
HOMEPAGE="http://hackage.haskell.org/package/SourceGraph"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cabal-1.6:= <dev-haskell/cabal-1.7:=
	dev-haskell/extensible-exceptions:=
	dev-haskell/fgl:=
	>=dev-haskell/graphalyze-0.7.0.0:= <dev-haskell/graphalyze-0.8.0.0:=
	>=dev-haskell/graphviz-2999.6.0.0:= <dev-haskell/graphviz-2999.7.0.0:=
	>=dev-haskell/haskell-src-exts-1.1.0:= <dev-haskell/haskell-src-exts-1.2.0:=
	dev-haskell/multiset:=
	dev-haskell/random:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
