# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="HTTP"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A library for client-side HTTP"
HOMEPAGE="https://github.com/haskell/HTTP"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="mtl1 network23 warn-as-error"

RDEPEND="dev-haskell/old-time:=[profile?]
	dev-haskell/parsec:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	mtl1? ( >=dev-haskell/mtl-1.1:=[profile?] <dev-haskell/mtl-1.2:=[profile?] )
	!mtl1? ( >=dev-haskell/mtl-2.0:=[profile?] <dev-haskell/mtl-2.2:=[profile?] )
	network23? ( <dev-haskell/network-2.4:=[profile?] )
	!network23? ( >=dev-haskell/network-2.4:=[profile?] <dev-haskell/network-2.5:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/case-insensitive-0.4 <dev-haskell/case-insensitive-0.5
		>=dev-haskell/conduit-0.4 <dev-haskell/conduit-0.5
		>=dev-haskell/http-types-0.6 <dev-haskell/http-types-0.7
		dev-haskell/httpd-shed
		dev-haskell/hunit
		>=dev-haskell/puremd5-2.1 <dev-haskell/puremd5-2.2
		>=dev-haskell/split-0.1 <dev-haskell/split-0.2
		dev-haskell/test-framework
		dev-haskell/test-framework-hunit
		>=dev-haskell/wai-1.2 <dev-haskell/wai-1.3
		>=dev-haskell/warp-1.2 <dev-haskell/warp-1.3
		mtl1? ( >=dev-haskell/mtl-2.0 <dev-haskell/mtl-2.2 ) )
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag mtl1 mtl1) \
		$(cabal_flag network23 network23) \
		$(cabal_flag warn-as-error warn-as-error)
}
