# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="HTTP"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A library for client-side HTTP"
HOMEPAGE="https://github.com/haskell/HTTP"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="conduit10 mtl1 network23 warn-as-error +warp-tests"

RDEPEND=">=dev-haskell/network-2.2.0.1:=[profile?] <dev-haskell/network-2.6:=[profile?]
	>=dev-haskell/old-time-1.0.0.0:=[profile?] <dev-haskell/old-time-1.2:=[profile?]
	>=dev-haskell/parsec-2.0:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	mtl1? ( >=dev-haskell/mtl-1.1.0.0:=[profile?] <dev-haskell/mtl-1.2:=[profile?] )
	!mtl1? ( >=dev-haskell/mtl-2.0:=[profile?] <dev-haskell/mtl-2.3:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	dev-lang/ghc
	test? ( >=dev-haskell/httpd-shed-0.4 <dev-haskell/httpd-shed-0.5
		>=dev-haskell/hunit-1.2.0.1 <dev-haskell/hunit-1.3
		>=dev-haskell/puremd5-0.2.4 <dev-haskell/puremd5-2.2
		>=dev-haskell/split-0.1.3 <dev-haskell/split-0.3
		>=dev-haskell/test-framework-0.2.0 <dev-haskell/test-framework-0.9
		>=dev-haskell/test-framework-hunit-0.2.0 <dev-haskell/test-framework-hunit-0.4
		warp-tests? ( >=dev-haskell/case-insensitive-0.4.0.1 <dev-haskell/case-insensitive-1.3
				>=dev-haskell/http-types-0.8.0 <dev-haskell/http-types-0.9
				>=dev-haskell/wai-2.1.0 <dev-haskell/wai-2.2
				>=dev-haskell/warp-2.1.0 <dev-haskell/warp-2.2 ) )
	conduit10? ( test? ( warp-tests? ( >=dev-haskell/conduit-1.0.8 <dev-haskell/conduit-1.1 ) ) )
	!conduit10? ( test? ( warp-tests? ( >=dev-haskell/conduit-1.1 <dev-haskell/conduit-1.2
						>=dev-haskell/conduit-extra-1.1 <dev-haskell/conduit-extra-1.2 ) ) )
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag conduit10 conduit10) \
		$(cabal_flag mtl1 mtl1) \
		$(cabal_flag network23 network23) \
		$(cabal_flag warn-as-error warn-as-error) \
		$(cabal_flag warp-tests warp-tests)
}
