# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="TrieMap"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Automatic type inference of generalized tries with Template Haskell"
HOMEPAGE="http://hackage.haskell.org/package/TrieMap"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/primitive-0.3:=[profile?]
	dev-haskell/th-expand-syns:=[profile?]
	>=dev-haskell/transformers-0.2.0.0:=[profile?]
	>=dev-haskell/unpack-funcs-0.1.2:=[profile?]
	>=dev-haskell/vector-0.6:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
