# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Betfair API bindings. Bet on sports on betting exchanges"
HOMEPAGE="https://github.com/Noeda/hs-bet/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="toys"

RDEPEND=">=dev-haskell/aeson-0.8.0.2:=[profile?] <dev-haskell/aeson-1.0:=[profile?]
	>=dev-haskell/bifunctors-4.2:=[profile?] <dev-haskell/bifunctors-5.0:=[profile?]
	>=dev-haskell/exceptions-0.6:=[profile?] <dev-haskell/exceptions-1.0:=[profile?]
	>=dev-haskell/hsopenssl-0.11:=[profile?] <dev-haskell/hsopenssl-1.0:=[profile?]
	>=dev-haskell/http-client-openssl-0.2:=[profile?] <dev-haskell/http-client-openssl-1.0:=[profile?]
	>=dev-haskell/lens-4.6:=[profile?] <dev-haskell/lens-5.0:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-3.0:=[profile?]
	>=dev-haskell/pipes-4.1.3:=[profile?] <dev-haskell/pipes-5.0:=[profile?]
	>=dev-haskell/pipes-http-1.0.1:=[profile?] <dev-haskell/pipes-http-2.0:=[profile?]
	>=dev-haskell/semigroupoids-4.2:=[profile?] <dev-haskell/semigroupoids-5.0:=[profile?]
	>=dev-haskell/semigroups-0.15.4:=[profile?] <dev-haskell/semigroups-1.0:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.0:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/quickcheck-2.7.6 <dev-haskell/quickcheck-3.0
		>=dev-haskell/test-framework-0.8.0.3 <dev-haskell/test-framework-1.0
		>=dev-haskell/test-framework-quickcheck2-0.3.0.3 <dev-haskell/test-framework-quickcheck2-1.0
		>=dev-haskell/test-framework-th-0.2.4 <dev-haskell/test-framework-th-1.0 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag toys toys)
}
