# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A converter for spinal, snake and camel cases"
HOMEPAGE="https://github.com/nikita-volkov/cases"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/attoparsec-0.10:=[profile?] <dev-haskell/attoparsec-0.13:=[profile?]
	>=dev-haskell/base-prelude-0.1.4:=[profile?] <dev-haskell/base-prelude-0.2:=[profile?]
	>=dev-haskell/loch-th-0.2:=[profile?] <dev-haskell/loch-th-0.3:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	test? ( >=dev-haskell/htf-0.11 <dev-haskell/htf-0.12
		dev-haskell/hunit
		>=dev-haskell/placeholders-0.1 <dev-haskell/placeholders-0.2
		dev-haskell/quickcheck )
"
