# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Spock-digestive"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Digestive functors support for Spock"
HOMEPAGE="https://github.com/agrafix/Spock-digestive"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/digestive-functors-0.7:=[profile?]
	>=dev-haskell/http-types-0.8:=[profile?]
	>=dev-haskell/mtl-2.0:=[profile?]
	>=dev-haskell/spock-0.7.6:=[profile?]
	>=dev-haskell/text-0.11.3.1:=[profile?]
	>=dev-haskell/unordered-containers-0.2:=[profile?]
	>=dev-haskell/wai-3.0:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
