# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="BERT implementation"
HOMEPAGE="https://github.com/feuerbach/bert"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.5:=[profile?]
	>=dev-haskell/binary-conduit-1.2:=[profile?]
	>=dev-haskell/conduit-1.0:=[profile?]
	>=dev-haskell/mtl-1.1:=[profile?]
	>=dev-haskell/network-2.2:=[profile?]
	>=dev-haskell/network-conduit-1.0:=[profile?]
	>=dev-haskell/parsec-2.0:=[profile?]
	dev-haskell/void:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16
	test? ( dev-haskell/async
		dev-haskell/smallcheck
		>=dev-haskell/tasty-0.4
		dev-haskell/tasty-hunit
		dev-haskell/tasty-smallcheck )
"
