# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="ConcurrentUtils"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Concurrent utilities"
HOMEPAGE="http://alkalisoftware.net"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=[profile?]
	>=dev-haskell/crypto-random-0.0.8:=[profile?]
	>=dev-haskell/cryptohash-0.11.6:=[profile?]
	>=dev-haskell/network-2.4:=[profile?]
	dev-haskell/parallel:=[profile?]
	dev-haskell/reexport-crypto-random:=[profile?]
	>=dev-haskell/rsa-2.1.0:=[profile?]
	>=dev-haskell/securemem-0.1.7:=[profile?]
	>=dev-haskell/tagged-0.7.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
