# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="ComonadSheet"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A library for expressing spreadsheet-like computations as the fixed-points of comonads"
HOMEPAGE="https://github.com/kwf/ComonadSheet"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/applicative-numbers-0.1.3:=[profile?]
	>=dev-haskell/comonad-4.0:=[profile?]
	>=dev-haskell/distributive-0.1:=[profile?]
	>=dev-haskell/indexedlist-0.1:=[profile?]
	>=dev-haskell/nestedfunctor-0.2:=[profile?]
	>=dev-haskell/peanowitnesses-0.1:=[profile?]
	>=dev-haskell/stream-0.4:=[profile?]
	>=dev-haskell/tape-0.4:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

S="${WORKDIR}/${MY_P}"
