# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HGamer3D-Common"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Toolset for the Haskell Game Programmer - Game Engine and Utilities"
HOMEPAGE="http://www.hgamer3d.org"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/clock:=[profile?]
	dev-haskell/findbin:=[profile?]
	>=dev-haskell/hgamer3d-data-0.5.0:=[profile?] <dev-haskell/hgamer3d-data-0.6.0:=[profile?]
	dev-haskell/stm:=[profile?]
	dev-haskell/vect:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4
"

S="${WORKDIR}/${MY_P}"
