# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Shield.io style badge generator"
HOMEPAGE="https://github.com/philopon/barrier"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="example generator test-results"

RDEPEND=">=dev-haskell/blaze-svg-0.3:=[profile?] <dev-haskell/blaze-svg-0.4:=[profile?]
	>=dev-haskell/text-1.1:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/unordered-containers-0.2:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-lang/ghc-7.6.1:=
	example? ( >=dev-haskell/lens-family-core-1.2:=[profile?] <dev-haskell/lens-family-core-1.3:=[profile?] )
	generator? ( >=dev-haskell/freetype2-0.1:=[profile?] <dev-haskell/freetype2-0.2:=[profile?] )
	test-results? ( >=dev-haskell/lens-family-core-1.2:=[profile?] <dev-haskell/lens-family-core-1.3:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/tasty-0.10 <dev-haskell/tasty-0.11
		>=dev-haskell/tasty-golden-2.2 <dev-haskell/tasty-golden-2.4
		!example? ( !test-results? ( >=dev-haskell/lens-family-core-1.2 <dev-haskell/lens-family-core-1.3 ) ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag example example) \
		$(cabal_flag generator generator) \
		$(cabal_flag test-results test-results)
}
