# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Ranka"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="HTTP to XMPP omegle chats gate"
HOMEPAGE="http://kagami.touhou.ru/projects/show/ranka"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/http:=
	dev-haskell/json:=
	dev-haskell/network:=
	dev-haskell/utf8-string:=
	>dev-haskell/xmpp-0.0.1:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
