# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Nomyx"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Nomic game in haskell"
HOMEPAGE="http://www.nomyx.net"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/acid-state-0.12:= <dev-haskell/acid-state-0.13:=
	>=dev-haskell/blaze-html-0.5:= <dev-haskell/blaze-html-0.6:=
	>=dev-haskell/blaze-markup-0.5:= <dev-haskell/blaze-markup-0.6:=
	>=dev-haskell/data-lens-2.10:= <dev-haskell/data-lens-2.11:=
	>=dev-haskell/data-lens-fd-2.0:= <dev-haskell/data-lens-fd-2.1:=
	>=dev-haskell/data-lens-template-2.1:= <dev-haskell/data-lens-template-2.2:=
	>=dev-haskell/debugtracehelpers-0.12:= <dev-haskell/debugtracehelpers-0.13:=
	>=dev-haskell/either-unwrap-1.1:= <dev-haskell/either-unwrap-1.2:=
	>=dev-haskell/fb-0.14:= <dev-haskell/fb-0.15:=
	>=dev-haskell/happstack-authenticate-0.10:= <dev-haskell/happstack-authenticate-0.11:=
	>=dev-haskell/happstack-server-7.1:= <dev-haskell/happstack-server-7.2:=
	>=dev-haskell/hint-0.3:= <dev-haskell/hint-0.4:=
	>=dev-haskell/hint-server-1.2:= <dev-haskell/hint-server-1.3:=
	>=dev-haskell/hscolour-1.20:= <dev-haskell/hscolour-1.21:=
	>=dev-haskell/ixset-1.0:= <dev-haskell/ixset-1.1:=
	>=dev-haskell/mime-mail-0.4:= <dev-haskell/mime-mail-0.5:=
	>=dev-haskell/missingh-1.2:= <dev-haskell/missingh-1.3:=
	>=dev-haskell/monadcatchio-mtl-0.3:= <dev-haskell/monadcatchio-mtl-0.4:=
	>=dev-haskell/mtl-2.1:= <dev-haskell/mtl-2.2:=
	>=dev-haskell/network-2.4:= <dev-haskell/network-2.5:=
	~dev-haskell/nomyx-language-0.4.1:=
	>=dev-haskell/old-locale-1.0:= <dev-haskell/old-locale-1.1:=
	>=dev-haskell/reform-0.2:= <dev-haskell/reform-0.3:=
	>=dev-haskell/reform-blaze-0.2:= <dev-haskell/reform-blaze-0.3:=
	>=dev-haskell/reform-happstack-0.2:= <dev-haskell/reform-happstack-0.3:=
	>=dev-haskell/safe-0.3:= <dev-haskell/safe-0.4:=
	>=dev-haskell/safecopy-0.8:= <dev-haskell/safecopy-0.9:=
	>=dev-haskell/split-0.2:= <dev-haskell/split-0.3:=
	>=dev-haskell/stm-2.4:= <dev-haskell/stm-2.5:=
	>=dev-haskell/tar-0.4:= <dev-haskell/tar-0.5:=
	>=dev-haskell/temporary-1.1:= <dev-haskell/temporary-1.2:=
	>=dev-haskell/text-0.11:= <dev-haskell/text-0.12:=
	>=dev-haskell/unix-compat-0.4:= <dev-haskell/unix-compat-0.5:=
	>=dev-haskell/web-routes-0.27:= <dev-haskell/web-routes-0.28:=
	>=dev-haskell/web-routes-happstack-0.23:= <dev-haskell/web-routes-happstack-0.24:=
	>=dev-haskell/web-routes-regular-0.19:= <dev-haskell/web-routes-regular-0.20:=
	>=dev-haskell/web-routes-th-0.22:= <dev-haskell/web-routes-th-0.23:=
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
