# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Ketchup"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A super small web framework for those who don't like big and fancy codebases"
HOMEPAGE="https://github.com/Hamcha/Ketchup"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="<dev-haskell/mime-types-0.2:=[profile?]
	<dev-haskell/network-2.5:=[profile?]
	<dev-haskell/regex-posix-1.0:=[profile?]
	<dev-haskell/text-2.0:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
