# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="This is an IRC bot for Mafia and Resistance"
HOMEPAGE="http://hackage.haskell.org/package/anticiv"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="AGPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/antisplice-0.17:=[profile?] <dev-haskell/antisplice-0.18:=[profile?]
	>=dev-haskell/chatty-0.6:=[profile?] <dev-haskell/chatty-0.7:=[profile?]
	>=dev-haskell/chatty-text-0.6:=[profile?] <dev-haskell/chatty-text-0.7:=[profile?]
	>=dev-haskell/chatty-utils-0.6:=[profile?] <dev-haskell/chatty-utils-0.8:=[profile?]
	>=dev-haskell/ctpl-0.1:=[profile?] <dev-haskell/ctpl-0.2:=[profile?]
	>=dev-haskell/ironforge-0.1:=[profile?] <dev-haskell/ironforge-0.2:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/network-2.3:=[profile?] <dev-haskell/network-2.4:=[profile?]
	>=dev-haskell/plugins-1.5:=[profile?] <dev-haskell/plugins-1.6:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-0.5:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
