# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Smooth"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A tiny, lazy SMT solver"
HOMEPAGE="http://hackage.haskell.org/package/Smooth"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/differencelogic-0.1:=[profile?] <dev-haskell/differencelogic-0.2:=[profile?]
	>=dev-haskell/firstordertheory-0.1:=[profile?] <dev-haskell/firstordertheory-0.2:=[profile?]
	>=dev-haskell/hunit-1.2:=[profile?] <dev-haskell/hunit-1.3:=[profile?]
	>=dev-haskell/proper-0.5:=[profile?] <dev-haskell/proper-0.6:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
