# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Haskell JSON schema validator and parser generator"
HOMEPAGE="https://github.com/timjb/aeson-schema"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.6.0.2:=[profile?]
	>=dev-haskell/attoparsec-0.8.6.1:=[profile?]
	dev-haskell/cmdargs:=[profile?]
	>=dev-haskell/mtl-2:=[profile?] <dev-haskell/mtl-3:=[profile?]
	>=dev-haskell/quickcheck-2.4.2:2=[profile?] <dev-haskell/quickcheck-2.5:2=[profile?]
	>=dev-haskell/regex-pcre-0.94.4:=[profile?]
	>=dev-haskell/syb-0.3.6.1:=[profile?]
	>=dev-haskell/text-0.11.1.0:=[profile?]
	>=dev-haskell/th-lift-0.5.5:=[profile?] <dev-haskell/th-lift-0.6:=[profile?]
	>=dev-haskell/transformers-0.3.0.0:=[profile?]
	>=dev-haskell/unordered-containers-0.1.3.0:=[profile?]
	>=dev-haskell/vector-0.7.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( dev-haskell/hashable
		dev-haskell/hint
		>=dev-haskell/hunit-1.2.4.3
		dev-haskell/temporary
		>=dev-haskell/test-framework-0.6 <dev-haskell/test-framework-0.7
		>=dev-haskell/test-framework-hunit-0.2.7
		>=dev-haskell/test-framework-quickcheck2-0.2.12.2 <dev-haskell/test-framework-quickcheck2-0.3 )
"
