# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="a dependently typed, polymorphic, higher order logic programming language"
HOMEPAGE="https://github.com/mmirman/caledon"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-2.0:= <dev-haskell/mtl-3.0:=
	>=dev-haskell/parsec-3.0:= <dev-haskell/parsec-4.0:=
	>=dev-haskell/transformers-0.3:= <dev-haskell/transformers-1.0:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
