# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="SDL2-ttf"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Binding to libSDL-ttf"
HOMEPAGE="http://hackage.haskell.org/package/SDL2-ttf"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/sdl2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/SDL2
	unknown-c-lib/SDL2_ttf
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
