# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Core functionality, serialisation primitives, and data types for the Amazonka Amazon Web Services SDKs"
HOMEPAGE="https://github.com/brendanhay/amazonka"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.8:=[profile?] <dev-haskell/aeson-0.9:=[profile?]
	>=dev-haskell/attoparsec-0.12:=[profile?] <dev-haskell/attoparsec-0.15:=[profile?]
	>=dev-haskell/base16-bytestring-0.1:=[profile?] <dev-haskell/base16-bytestring-1:=[profile?]
	>=dev-haskell/base64-bytestring-1:=[profile?] <dev-haskell/base64-bytestring-2:=[profile?]
	>=dev-haskell/bifunctors-0.3:=[profile?]
	>=dev-haskell/case-insensitive-1.1:=[profile?]
	>=dev-haskell/conduit-1.1:=[profile?] <dev-haskell/conduit-1.3:=[profile?]
	>=dev-haskell/conduit-extra-1.1:=[profile?] <dev-haskell/conduit-extra-1.2:=[profile?]
	>=dev-haskell/cryptohash-0.11:=[profile?] <dev-haskell/cryptohash-0.12:=[profile?]
	>=dev-haskell/cryptohash-conduit-0.1.1:=[profile?]
	>=dev-haskell/data-default-class-0.0.1:=[profile?]
	>=dev-haskell/hashable-1.2:=[profile?]
	>=dev-haskell/http-client-0.3.6:=[profile?] <dev-haskell/http-client-0.4:=[profile?]
	>=dev-haskell/http-types-0.8:=[profile?]
	>=dev-haskell/lens-4.4:=[profile?] <dev-haskell/lens-5:=[profile?]
	>=dev-haskell/mmorph-1:=[profile?] <dev-haskell/mmorph-2:=[profile?]
	>=dev-haskell/mtl-2.2.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/nats-0.1.3:=[profile?]
	>=dev-haskell/old-locale-1:=[profile?]
	>=dev-haskell/resourcet-1.1:=[profile?] <dev-haskell/resourcet-1.2:=[profile?]
	>=dev-haskell/semigroups-0.12:=[profile?]
	>=dev-haskell/tagged-0.7:=[profile?]
	>=dev-haskell/text-1.1:=[profile?]
	>=dev-haskell/transformers-0.4:=[profile?] <dev-haskell/transformers-0.5:=[profile?]
	>=dev-haskell/unordered-containers-0.2.3:=[profile?]
	>=dev-haskell/vector-0.10.9:=[profile?]
	>=dev-haskell/xml-conduit-1.2:=[profile?] <dev-haskell/xml-conduit-1.3:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
