# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="a url shortener"
HOMEPAGE="https://github.com/rnhmjoj/breve"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.8:= <dev-haskell/aeson-0.9:=
	>=dev-haskell/binary-0.7:= <dev-haskell/binary-0.8:=
	>=dev-haskell/cryptohash-0.11:= <dev-haskell/cryptohash-0.12:=
	>=dev-haskell/hashtables-1.2:= <dev-haskell/hashtables-1.3:=
	>=dev-haskell/mtl-2.1:= <dev-haskell/mtl-2.2:=
	>=dev-haskell/random-1.1:= <dev-haskell/random-1.2:=
	>=dev-haskell/simple-0.8.0:=
	>=dev-haskell/transformers-0.3:= <dev-haskell/transformers-0.4:=
	>=dev-haskell/wai-2:= <dev-haskell/wai-3:=
	>=dev-haskell/wai-extra-2:= <dev-haskell/wai-extra-3:=
	>=dev-haskell/warp-2.1:= <dev-haskell/warp-2.2:=
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
