# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="a url shortener"
HOMEPAGE="https://github.com/rnhmjoj/breve"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=
	dev-haskell/binary:=
	dev-haskell/configurator:=
	dev-haskell/cryptohash:=
	dev-haskell/hashtables:=
	dev-haskell/mtl:=
	dev-haskell/random:=
	dev-haskell/simple:=
	dev-haskell/transformers:=
	dev-haskell/wai:=
	dev-haskell/wai-extra:=
	dev-haskell/warp:=
	dev-haskell/xdg-basedir:=
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"
