# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HarmTrace"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Harmony Analysis and Retrieval of Music"
HOMEPAGE="http://www.cs.uu.nl/wiki/GenericProgramming/HarmTrace"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.6.4:=[profile?]
	>=dev-haskell/cmdargs-0.10.1:=[profile?]
	>=dev-haskell/diff-0.1:=[profile?] <dev-haskell/diff-0.2:=[profile?]
	>=dev-haskell/harmtrace-base-1.0.0.2:=[profile?]
	>=dev-haskell/hcodecs-0.2.2:=[profile?]
	>=dev-haskell/hmatrix-0.11.0.3:=[profile?]
	>=dev-haskell/hmatrix-gsl-stats-0.1.2.9:=[profile?]
	>=dev-haskell/instant-generics-0.3.6:=[profile?] <dev-haskell/instant-generics-0.4:=[profile?]
	>=dev-haskell/listlike-3.0.1:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/parallel-3:=[profile?]
	>=dev-haskell/parseargs-0.1.3.2:=[profile?]
	>=dev-haskell/sox-0.2.2.2:=[profile?]
	>=dev-haskell/uu-parsinglib-2.7.4:=[profile?] <dev-haskell/uu-parsinglib-2.7.5:=[profile?]
	>=dev-haskell/vector-0.7:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
