# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="HipmunkPlayground"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A playground for testing Hipmunk"
HOMEPAGE="http://patch-tag.com/r/felipe/hipmunkplayground/home"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/glfw-0.4:= <dev-haskell/glfw-0.6:=
	>=dev-haskell/hipmunk-5.2:= <dev-haskell/hipmunk-5.3:=
	>=dev-haskell/opengl-2.4:= <dev-haskell/opengl-2.6:=
	>=dev-haskell/statevar-1.0:= <dev-haskell/statevar-1.1:=
	>=dev-haskell/transformers-0.2:= <dev-haskell/transformers-0.3:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
