# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="bamboo-launcher"
HOMEPAGE="http://github.com/nfjinjing/hack/tree/master"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bamboo-2009.5.2:=
	>=dev-haskell/hack-2009.5.19:=
	>=dev-haskell/hack-contrib-2009.5.19:=
	>=dev-haskell/hack-handler-happstack-2009.5.19:=
	>=dev-haskell/mps-2009.5.13:=
	dev-haskell/utf8-prelude:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"
