# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HXQ"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Compiler from XQuery to Haskell"
HOMEPAGE="http://lambda.uta.edu/HXQ/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="mysql sqlite"

RDEPEND="dev-haskell/readline:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	mysql? ( <dev-haskell/hdbc-1.1.5:2=[profile?]
			dev-haskell/hdbc-odbc:=[profile?] )
	!mysql? ( sqlite? ( <dev-haskell/hdbc-1.1.5:2=[profile?]
				dev-haskell/hdbc-odbc:=[profile?]
				dev-haskell/hdbc-sqlite3:=[profile?] ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag mysql mysql) \
		$(cabal_flag sqlite sqlite)
}
