# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="BiobaseXNA"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Efficient RNA/DNA representations"
HOMEPAGE="http://www.tbi.univie.ac.at/~choener/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="~dev-haskell/csv-0.1.2:=[profile?]
	>=dev-haskell/file-embed-0.0.4:=[profile?]
	>=dev-haskell/primitive-0.4:=[profile?]
	~dev-haskell/primitivearray-0.4.0.0:=[profile?]
	>=dev-haskell/text-0.11:=[profile?]
	>=dev-haskell/tuple-0.2:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6.0
"

S="${WORKDIR}/${MY_P}"
