# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Control library for blink(1) LED from ThingM"
HOMEPAGE="http://hackage.haskell.org/package/blink1"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+usb"

RDEPEND=">=dev-lang/ghc-7.4.1:=
	usb? ( <dev-haskell/text-1.2:=[profile?]
		dev-haskell/usb:=[profile?]
		dev-haskell/vector:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag usb usb)
}
