# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Low level bindings supporting GTS, the GNU Triangulated Surface Library"
HOMEPAGE="http://hackage.haskell.org/package/bindings-gts"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="LGPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bindings-dsl-1.0.9:=[profile?] <dev-haskell/bindings-dsl-1.1:=[profile?]
	>=dev-haskell/bindings-glib-0.1.5:=[profile?] <dev-haskell/bindings-glib-0.2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-pkg-config/gts
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4
	virtual/pkgconfig
"
