# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="An embedded language for accelerated array processing"
HOMEPAGE="http://www.cse.unsw.edu.au/~chak/project/accelerate/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+cuda llvm"

RDEPEND=">=dev-lang/ghc-7.4.1:=
	cuda? ( dev-haskell/binary:=[profile?]
		>=dev-haskell/cuda-0.2:=[profile?] <dev-haskell/cuda-0.3:=[profile?]
		dev-haskell/fclabels:=[profile?]
		>=dev-haskell/language-c-0.3:=[profile?] <dev-haskell/language-c-0.4:=[profile?]
		dev-haskell/monads-fd:=[profile?]
		>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.3:=[profile?] )
	llvm? ( >=dev-haskell/llvm-0.6.8:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag cuda cuda) \
		$(cabal_flag llvm llvm)
}
