# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="An embedded language for accelerated array processing"
HOMEPAGE="https://github.com/AccelerateHS/accelerate/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+bounds-checks internal-checks llvm more-pp unsafe-checks"

RDEPEND=">=dev-lang/ghc-7.4.1:=
	more-pp? ( >=dev-haskell/blaze-html-0.3:=[profile?] <dev-haskell/blaze-html-0.4:=[profile?]
			>=dev-haskell/text-0.10:=[profile?] <dev-haskell/text-0.11:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag bounds-checks bounds-checks) \
		$(cabal_flag internal-checks internal-checks) \
		$(cabal_flag llvm llvm) \
		$(cabal_flag more-pp more-pp) \
		$(cabal_flag unsafe-checks unsafe-checks)
}
