# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="SpacePrivateers"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Simple space pirate roguelike"
HOMEPAGE="https://github.com/tuturto/space-privateers"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/enummapset-th-0.6.0.0:= <dev-haskell/enummapset-th-1:=
	>=dev-haskell/lambdahack-0.2.14:= <dev-haskell/lambdahack-0.2.15:=
	>=dev-haskell/text-0.11.2.3:= <dev-haskell/text-2:=
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
