# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HLearn-distributions"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Distributions for use with the HLearn library"
HOMEPAGE="http://github.com/mikeizbicki/HLearn/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/constraintkinds-0.0.1:=[profile?]
	>=dev-haskell/criterion-0.6.1.1:=[profile?]
	>=dev-haskell/hlearn-algebra-0.1.2:=[profile?]
	>=dev-haskell/list-extras-0.4.1:=[profile?]
	dev-haskell/logfloat:=[profile?]
	>=dev-haskell/math-functions-0.1.1:=[profile?]
	>=dev-haskell/monadrandom-0.1.6:=[profile?]
	>=dev-haskell/normaldistribution-1.1.0:=[profile?]
	>=dev-haskell/quickcheck-2.5.1:2=[profile?]
	>=dev-haskell/statistics-0.10.2:=[profile?]
	>=dev-haskell/vector-0.9:=[profile?]
	>=dev-haskell/vector-th-unbox-0.2:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"

S="${WORKDIR}/${MY_P}"
