# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Approximate randomization test"
HOMEPAGE="http://github.com/danieldk/approx-rand-test"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/conduit-0.4:=[profile?] <dev-haskell/conduit-0.5:=[profile?]
	>=dev-haskell/mersenne-random-pure64-0.2.0:=[profile?] <dev-haskell/mersenne-random-pure64-0.2.1:=[profile?]
	~dev-haskell/monad-mersenne-random-0.1:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/resourcet-0.3:=[profile?] <dev-haskell/resourcet-0.4:=[profile?]
	>=dev-haskell/statistics-0.10.1:=[profile?] <dev-haskell/statistics-0.10.2:=[profile?]
	>=dev-haskell/text-0.11.2:=[profile?] <dev-haskell/text-0.11.3:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-haskell/vector-0.9:=[profile?] <dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/hunit-1.2.4 <dev-haskell/hunit-1.2.5
		>=dev-haskell/test-framework-0.6 <dev-haskell/test-framework-0.7
		>=dev-haskell/test-framework-hunit-0.2 <dev-haskell/test-framework-hunit-0.3 )
"
