# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="ADP for multiple context-free languages"
HOMEPAGE="http://adp-multi.ruhoh.com"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="buildtests"

RDEPEND=">=dev-haskell/criterion-0.6:=[profile?] <dev-haskell/criterion-0.7:=[profile?]
	>=dev-haskell/htrace-0.1:=[profile?] <dev-haskell/htrace-0.2:=[profile?]
	>=dev-haskell/hunit-1.2:=[profile?] <dev-haskell/hunit-1.3:=[profile?]
	>=dev-haskell/monadiccp-0.7:=[profile?] <dev-haskell/monadiccp-0.8:=[profile?]
	>=dev-haskell/quickcheck-2.5:2=[profile?] <dev-haskell/quickcheck-2.6:2=[profile?]
	~dev-haskell/random-shuffle-0.0.4:=[profile?]
	>=dev-haskell/test-framework-0.6:=[profile?] <dev-haskell/test-framework-0.7:=[profile?]
	>=dev-haskell/test-framework-hunit-0.2:=[profile?] <dev-haskell/test-framework-hunit-0.3:=[profile?]
	>=dev-haskell/test-framework-quickcheck2-0.2:=[profile?] <dev-haskell/test-framework-quickcheck2-0.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag buildtests buildtests)
}
