# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="GenI"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A natural language generator (specifically, an FB-LTAG surface realiser)"
HOMEPAGE="http://projects.haskell.org/GenI"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="static"

RDEPEND=">=dev-haskell/binary-0.5.0.2:=[profile?]
	>=dev-haskell/cabal-macosx-0.1.2:=[profile?] <dev-haskell/cabal-macosx-0.3:=[profile?]
	dev-haskell/errors:=[profile?]
	dev-haskell/hslogger:=[profile?]
	>=dev-haskell/json-0.4.3:=[profile?] <dev-haskell/json-0.6:=[profile?]
	>dev-haskell/mtl-1.0:=[profile?]
	dev-haskell/old-locale:=[profile?]
	>=dev-haskell/ordered-0.1:=[profile?] <dev-haskell/ordered-0.2:=[profile?]
	>=dev-haskell/parsec-2:=[profile?]
	>=dev-haskell/split-0.1.1:=[profile?] <dev-haskell/split-0.2:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/transformers:=[profile?]
	>=dev-haskell/yaml-light-0.1:=[profile?] <dev-haskell/yaml-light-0.2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.14
	test? ( >dev-haskell/hunit-1 <dev-haskell/hunit-1.3
		>=dev-haskell/parsec-2 <dev-haskell/parsec-3.2
		dev-haskell/quickcheck
		dev-haskell/smallcheck
		>dev-haskell/test-framework-0.3
		dev-haskell/test-framework-hunit
		dev-haskell/test-framework-quickcheck2
		dev-haskell/test-framework-smallcheck )
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag static static)
}
