# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Ganymede"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An Io interpreter in Haskell"
HOMEPAGE="http://hackage.haskell.org/package/Ganymede"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/mtl:=
	>=dev-haskell/parsec-3:= <dev-haskell/parsec-4:=
	>=dev-haskell/transformers-0.2:= <dev-haskell/transformers-0.3:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
