# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Manage sandboxed Haskell build environments"
HOMEPAGE="http://github.com/creswick/cabal-dev"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="build-tests no-cabal-dev"

RDEPEND=">=dev-lang/ghc-7.4.1:=
	no-cabal-dev? ( >=dev-haskell/cabal-1.2:= <dev-haskell/cabal-1.17:= )
	!no-cabal-dev? ( >=dev-haskell/cabal-1.10.0.0:= <dev-haskell/cabal-1.17:=
				>=dev-haskell/http-4000.0.9:= <dev-haskell/http-4000.3:=
				>=dev-haskell/mtl-1.1:= <dev-haskell/mtl-2.2:=
				>=dev-haskell/network-2.2:= <dev-haskell/network-2.5:=
				>=dev-haskell/setenv-0.1:= <dev-haskell/setenv-0.2:=
				>=dev-haskell/tar-0.4:= <dev-haskell/tar-0.5:=
				>=dev-haskell/transformers-0.2:= <dev-haskell/transformers-0.4:=
				>=dev-haskell/zlib-0.5:= <dev-haskell/zlib-0.6:=
				build-tests? ( >=dev-haskell/hunit-1.2:= <dev-haskell/hunit-2:=
					>=dev-haskell/monadrandom-0.1:= <dev-haskell/monadrandom-0.2:=
					>=dev-haskell/random-1:= <dev-haskell/random-1.1:=
					>=dev-haskell/test-framework-0.3:= <dev-haskell/test-framework-0.9:=
					>=dev-haskell/test-framework-hunit-0.2:= ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
	!no-cabal-dev? ( dev-haskell/cabal-install )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag build-tests build-tests) \
		$(cabal_flag no-cabal-dev no-cabal-dev)
}
