# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A simple interpreter for arrayForth, the language used on GreenArrays chips"
HOMEPAGE="http://hackage.haskell.org/package/array-forth"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mcmc-synthesis-0.1:=[profile?]
	>=dev-haskell/monadrandom-0.1:=[profile?] <dev-haskell/monadrandom-0.2:=[profile?]
	>=dev-haskell/oddword-1.0.0:=[profile?]
	>=dev-haskell/split-0.1:=[profile?] <dev-haskell/split-0.2:=[profile?]
	>=dev-haskell/vector-0.9:=[profile?] <dev-haskell/vector-0.10:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
