# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="IsNull"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A typeclass to determine if a given value is null"
HOMEPAGE="https://github.com/jcristovao/IsNull"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/base-compat-0.5:=[profile?] <dev-haskell/base-compat-0.6:=[profile?]
	>=dev-haskell/text-0.11.3:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/hspec-1.7.2
		>=dev-haskell/hunit-1.2.5.2
		>=dev-haskell/quickcheck-2.6
		>=dev-haskell/quickcheck-instances-0.3.5
		>=dev-haskell/system-filepath-0.4.6
		>=dev-haskell/text-0.11.3.1 <dev-haskell/text-1.3
		>=dev-haskell/unordered-containers-0.2.3
		>=dev-haskell/vector-0.10.0.1 )
"

S="${WORKDIR}/${MY_P}"
