# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Haskell compiler that produce binary through C language"
HOMEPAGE="http://ajhc.masterq.net/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=
	dev-haskell/fgl:=
	dev-haskell/haskeline:=
	dev-haskell/hssyck:=
	dev-haskell/mtl:=
	dev-haskell/old-time:=
	dev-haskell/random:=
	dev-haskell/regex-compat:=
	dev-haskell/syb:=
	dev-haskell/temporary:=
	dev-haskell/utf8-string:=
	dev-haskell/zlib:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
