# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="LambdaNet"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A configurable and extensible neural network library"
HOMEPAGE="http://hackage.haskell.org/package/LambdaNet"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=[profile?]
	~dev-haskell/hmatrix-0.16.0.6:=[profile?]
	dev-haskell/random:=[profile?]
	>=dev-haskell/random-shuffle-0.0.4:=[profile?]
	dev-haskell/split:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"
