# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Hsed"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Stream Editor in Haskell"
HOMEPAGE="http://github.com/rukav/Hsed"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cmdargs-0.3:=[profile?]
	>=dev-haskell/data-accessor-0.2.1.4:=[profile?]
	>=dev-haskell/data-accessor-template-0.2.1.5:=[profile?]
	>=dev-haskell/data-accessor-transformers-0.2.1.2:=[profile?]
	>=dev-haskell/glob-0.5.1:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/parsec:=[profile?]
	dev-haskell/regex-base:=[profile?]
	dev-haskell/regex-compat:=[profile?]
	dev-haskell/regex-posix:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"
