# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="RSA"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Implementation of RSA, using the padding schemes of PKCS#1 v2.1"
HOMEPAGE="http://hackage.haskell.org/package/RSA"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="hasarbitraryword8 +includemd5 quickcheck1 +skiptests +usebinary"

RDEPEND="dev-haskell/random:=[profile?]
	dev-haskell/sha:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	includemd5? ( usebinary? ( dev-haskell/puremd5:=[profile?] ) )
	!skiptests? ( >=dev-haskell/test-framework-0.3:=[profile?] <dev-haskell/test-framework-0.4:=[profile?]
			quickcheck1? ( <dev-haskell/quickcheck-2:2=[profile?]
					>=dev-haskell/test-framework-quickcheck-0.2.6:=[profile?] <dev-haskell/test-framework-quickcheck-0.3:=[profile?] )
			!quickcheck1? ( >=dev-haskell/test-framework-quickcheck2-0.2.7:=[profile?] <dev-haskell/test-framework-quickcheck2-0.3:=[profile?]
					hasarbitraryword8? ( >=dev-haskell/quickcheck-2.1.2:2=[profile?] <dev-haskell/quickcheck-3:2=[profile?] )
					!hasarbitraryword8? ( >=dev-haskell/quickcheck-2:2=[profile?] <dev-haskell/quickcheck-2.1.2:2=[profile?] ) ) )
	usebinary? ( dev-haskell/binary:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag hasarbitraryword8 hasarbitraryword8) \
		$(cabal_flag includemd5 includemd5) \
		$(cabal_flag quickcheck1 quickcheck1) \
		$(cabal_flag skiptests skiptests) \
		$(cabal_flag usebinary usebinary)
}
