# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="RSA"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Implementation of RSA, using the padding schemes of PKCS#1 v2.1"
HOMEPAGE="http://hackage.haskell.org/package/RSA"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+includemd5 test +usebinary"

RDEPEND=">=dev-haskell/crypto-api-0.10:=[profile?]
	>=dev-haskell/crypto-pubkey-types-0.2:=[profile?]
	dev-haskell/monadcryptorandom:=[profile?]
	dev-haskell/sha:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	test? ( >=dev-haskell/drbg-0.2.3:=[profile?] <dev-haskell/drbg-0.4:=[profile?]
		>=dev-haskell/quickcheck-2:2=[profile?] <dev-haskell/quickcheck-3:2=[profile?]
		>=dev-haskell/tagged-0.2.3:=[profile?] <dev-haskell/tagged-0.5:=[profile?]
		>=dev-haskell/test-framework-0.3:=[profile?] <dev-haskell/test-framework-0.7:=[profile?]
		>=dev-haskell/test-framework-quickcheck2-0.2:=[profile?] <dev-haskell/test-framework-quickcheck2-0.7:=[profile?] )
	includemd5? ( usebinary? ( dev-haskell/puremd5:=[profile?] ) )
	usebinary? ( dev-haskell/binary:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag includemd5 includemd5) \
		$(cabal_flag test test) \
		$(cabal_flag usebinary usebinary)
}
