# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="HackMail"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Procmail Replacement as Haskell EDSL"
HOMEPAGE="http://patch-tag.com/publicrepos/Hackmail"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/crypto-4.2:=[profile?]
	>=dev-haskell/hdaemonize-0.1:=[profile?]
	>=dev-haskell/hint-0.3:=[profile?]
	>=dev-haskell/mtl-1.1:=[profile?]
	>=dev-haskell/old-time-1.0:=[profile?]
	>=dev-haskell/parsec-2.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
