# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="AERN-Real"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="arbitrary precision interval arithmetic for approximating exact real numbers"
HOMEPAGE="http://hackage.haskell.org/package/AERN-Real"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="use-hmpfr"

RDEPEND=">=dev-haskell/binary-0.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	use-hmpfr? ( ~dev-haskell/hmpfr-0.1.1:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag use-hmpfr use-hmpfr)
}
