# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A simple, sinatra-inspired web framework"
HOMEPAGE="http://github.com/moonmaster9000/bird"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/data-default-0.2:=[profile?]
	>=dev-haskell/hack-2009.10.30:=[profile?]
	dev-haskell/hack-handler-happstack:=[profile?]
	>=dev-haskell/missingh-1.1.0.3:=[profile?]
	>=dev-haskell/mtl-1.1.0.2:=[profile?]
	>=dev-haskell/parsec-2.1.0.1:=[profile?]
	dev-haskell/rallod:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2
"
