# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="HJVM"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A library to create a Java Virtual Machine and manipulate Java objects"
HOMEPAGE="https://github.com/JPMoresmau/HJVM"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/haskell-src-exts:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/parsec-3:=[profile?]
	dev-haskell/transformers:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	unknown-c-lib/jvm
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/cabal-1.9.2
		dev-haskell/hunit
		dev-haskell/test-framework
		dev-haskell/test-framework-hunit )
"

S="${WORKDIR}/${MY_P}"
