# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="Wordlint"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Plaintext prose redundancy linter"
HOMEPAGE="https://github.com/gbgar/Wordlint"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE=""	# FIXME: Please look at license file of package and pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/boxes-0.1:=[profile?] <dev-haskell/boxes-0.2:=[profile?]
	>=dev-haskell/cmdargs-0.10.0:=[profile?] <dev-haskell/cmdargs-0.11.0:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

S="${WORKDIR}/${MY_P}"
