# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Boomshine clone"
HOMEPAGE="http://hackage.haskell.org/package/boomslang"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/data-accessor-0:= <dev-haskell/data-accessor-1:=
	>=dev-haskell/data-accessor-template-0:= <dev-haskell/data-accessor-template-1:=
	>=dev-haskell/font-opengl-basic4x6-0:= <dev-haskell/font-opengl-basic4x6-1:=
	>=dev-haskell/glfw-b-0:= <dev-haskell/glfw-b-1:=
	>=dev-haskell/monadrandom-0:= <dev-haskell/monadrandom-1:=
	>=dev-haskell/opengl-2.5:= <dev-haskell/opengl-2.6:=
	>=dev-lang/ghc-7.4.1:=
	|| ( ( >=dev-haskell/mtl-1:= <dev-haskell/mtl-2:= )
		( >=dev-haskell/mtl-2:= <dev-haskell/mtl-3:= ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
