# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Server and community browser for the game Tremulous"
HOMEPAGE="http://hackage.haskell.org/package/apelsin"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="relativepath"

RDEPEND="dev-haskell/glib:=
	dev-haskell/gtk:=
	dev-haskell/http:=
	dev-haskell/mtl:=
	dev-haskell/network:=
	dev-haskell/stm:=
	dev-haskell/transformers:=
	>=dev-haskell/tremulous-query-1.0.2:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag relativepath relativepath)
}
