# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="WebBits-multiplate"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Multiplate instance for JavaScript"
HOMEPAGE="http://hackage.haskell.org/package/WebBits-multiplate"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/multiplate:=[profile?]
	dev-haskell/multiplate-simplified:=[profile?]
	>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.3:=[profile?]
	dev-haskell/webbits:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.4
"

S="${WORKDIR}/${MY_P}"
