# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="bin"
inherit haskell-cabal

MY_PN="Pugs"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Perl 6 Implementation"
HOMEPAGE="http://pugscode.org/"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="+perl5"

RDEPEND="dev-haskell/binary:=
	>=dev-haskell/control-timeout-0.1.2:=
	dev-haskell/findbin:=
	>=dev-haskell/haskeline-0.2.1:=
	>=dev-haskell/hsparrot-0.0.2:=
	>=dev-haskell/hssyck-0.44:=
	>=dev-haskell/metaobject-0.0.4:=
	dev-haskell/mtl:=
	dev-haskell/network:=
	<dev-haskell/parsec-3.0.0:=
	>=dev-haskell/pugs-compat-0.0.5:=
	>=dev-haskell/pugs-drift-2.2.3.0:=
	dev-haskell/random:=
	dev-haskell/stm:=
	>=dev-haskell/stringtable-atom-0.0.4:=
	dev-haskell/utf8-string:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.2.3
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag perl5 perl5)
}
