# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

MY_PN="Twofish"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An implementation of the Twofish Symmetric-key cipher"
HOMEPAGE="http://github.com/rleisti/twofish"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.5.1.0:=[profile?]
	>=dev-haskell/cereal-0.3.5.2:=[profile?]
	>=dev-haskell/crypto-api-0.10.2:=[profile?]
	>=dev-haskell/largeword-1.0.3:=[profile?]
	>=dev-haskell/mtl-1.1.0.2:=[profile?]
	>=dev-haskell/tagged-0.4.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.14
	test? ( >=dev-haskell/hunit-1.2.4.2 )
"

S="${WORKDIR}/${MY_P}"
